### PR TITLE
Remove <tt> tags

### PR DESCRIPTION
**Pull request by JamieMagee**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

3

---

The `<tt>` tag has been deprecated since HTML5 was released ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt)). It's recommended to replace it with `<kbd>`, `<var>`, or `<code>`.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Th3M3** [comment]
If you don't want to change the element's style as it is now, you can also replace `<tt>` with `<samp>` :wink:

**Comment by PromoFaux** [comment]
I'm no HTML expert, but they all look the same to me!

image

That said, I like the idea of not using deprecated tags.

Approved

**Comment by Th3M3** [comment]
@PromoFaux 
Bootstrap uses different styling for the elements.

If you want to try it out in real time, you can change the element(s) with the browser's development tools

**Comment by PromoFaux** [comment]
Ah yes, bootstrap. I forget that has styles for things.  In which case, @JamieMagee  can you please change the `<kbd>` tags to `<samp>`, cheers!

**Comment by JamieMagee** [comment]
Done!

**Pull request merged**
