### PR TITLE
Add support for international domain names

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Add support for international domain names.

**How does this PR accomplish the above?:**

Convert domains to IDN form (if applicable) before adding them to the database.
Note that this relies on `php-intl` to be installed, I will add it in a separate PR to the core repo.

**Traditional domains list**
Screenshot from 2020-01-12 13-56-47

**Group management domains page**
Screenshot from 2020-01-12 13-56-32

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/url-allestorungen/26659/19

**Comment by DL6ER** [comment]
For those who want to test it but don't have Umlauts on their keyboards, you can copy&paste the test domains from below:
```
allestörungen.de
testäää.de
```

**Comment by DL6ER** [comment]
The necessary core PR has been merged.

**Comment by DL6ER** [comment]
This may be reviewed and merged at any time.

**Comment by dschaper** [comment]
Does this require the v2 build containers or the `libidn` things?

**Comment by DL6ER** [comment]
No, it's only using PHP stuff which we already added in https://github.com/pi-hole/pi-hole/pull/3076

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/database-error-after-update/27966/6

**Pull request merged**
