### PR TITLE
Add "versions" endpoint ot API

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Implement a [Discourse feature request](https://discourse.pi-hole.net/t/expand-api/9999) for an API endpoint that returns the information `pihole -v` can provide on the CLI.

**How does this PR accomplish the above?:**

We generate this information already for the update checker in the footer of the dashboard. This new API endpoint makes them accessible.

http://pi.hole/admin/api.php?versions
screenshot at 2018-06-07 20-22-01

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/expand-api/9999/11

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ability-to-check-for-updates-and-display-current-and-update-version-via-api/3738/2

**Comment by maheraldous** [comment]
Can you add the ability to add and delete domains from white- and blacklist in the API. Also if I can get the current white- and blacklist via API as you did with the version endpoint.

**Comment by dschaper** [comment]
Open a Feature Request on https://discourse.pi-hole.net. We don't track feature requests on GitHub.

**Pull request merged**
