### PR TITLE
Speedup

### PR DESCRIPTION
**Pull request by DJFliX**
Changes proposed in this pull request:

Tinified .png resources to save bandwidth (and thus the limited processing power we have on a Pi)
Retrieve some of the resources from a CDN (FontAwesome, Bootstrap css, IonIcons, Source Sans Pro), relieving the Pi from some file hosting duties.
@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
The reason we have everything hosted is because if the internet drops out (which happened to one user ), then the interface still fully works and looks the same.

**Comment by DJFliX** [comment]
Would you consider making it a configurable value?

**Comment by Mcat12** [comment]
A fallback would be a good compromise.

**Comment by DJFliX** [comment]
I tried some things and to keep it simple: 
- CDN + local fallback requires changes to the Content Security Policy
- While the load time for certain resources is shortened (the Pi doesn't have to queue the resource requests while running the php scripts) the actual problem is with the php scripts themselves. The main improvement over the current situation would be that the several resource files are concatenated into a single resource. As the performance gains are peanuts compared to what optimising the php code could do for performance, I'll leave it to you to decide whether investing time in optimising the loading of resources makes sense.

Thanks for you fast responses!

**Pull request closed without merging**
