### PR TITLE
Supporting aLTE change for core tweak/blockpage branch

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

4

---
* Set pcre.recursion_limit, 3x the limit necessary to process a valid 253 character domain name
* Updated validate_domain() to include underscore as a valid character within a domain 
* Run escapeshellarg() on `pihole -q` command in the unlikely event that a maliciously crafted domain query is able to pass validate_domain()
* Known issues: Changes to the output of this file and Pi-hole core's queryFunc() results in `queryads.js` failing to work (Thereby breaking Tools > Query adlists)

### CODE REVIEW

**Comment by WaLLy3K** [comment]
`queryads.js` is not currently being worked on and as it stands in dev branch, it's broken anyway because of [query changes](https://github.com/pi-hole/pi-hole/pull/1417).

**Comment by DL6ER** [comment]
Putting this on Hold as long as the updated querying function is not there

**Comment by Mcat12** [comment]
Is this still on hold? It's blocking pi-hole/pi-hole#1416

**Comment by WaLLy3K** [comment]
Awaiting the release of (core) 3.1, so we can merge the queryFunc/block page changes into dev and test it for 3.2.

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
