### PR TITLE
Add DHCP lease time settings.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---
Ignore the misleading branch name (had another direction at the beginning).

- Add settings for DHCP lease time to the settings page
- Some `<div>` cleanups
- Hide DHCP leases table in expandable box as well

**NOTE: Will only work when you have checked out `tweak/simplify_webpage.sh` on the core side!**

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Note that I still don't show the lease times in the leases table, since they can have two entirely different meanings (depending on the compile settings of `dnsmasq`):

- Seconds until lease ends
- Unix timestamp when lease ends

They should be separable by analyzing their order of magnitude. I'll have a look.

**Comment by darkrain-nl** [comment]
I like this very much, great work getting all this in!

**Comment by DL6ER** [comment]
:-)

I added the DHCP lease time display. However, I cannot do any testing with DHCP here, so I have no idea if this works or not. Please test.

**Comment by DL6ER** [comment]
Tested with mixed dummy entries in `dhcp.leases`:
```
1213131 A B C D
6213131 I J K L 
31 M N O P
1483032204 E F G H
```
screenshot at 2016-12-29 15-57-00

**Comment by darkrain-nl** [comment]
The functionality works as expected, only the interface has some minor flaws:
2016-12-29 17_51_08-pi-hole admin console
But that is only when you have the menu folded out.

**Comment by darkrain-nl** [comment]
MAC address is incorect with DHCPv6 leases
2016-12-29 18_40_11-pi-hole admin console

**Comment by dschaper** [comment]
Are those the DUIDs?

**Comment by darkrain-nl** [comment]
probably..

**Comment by DL6ER** [comment]
Can you post an exemplary line of an IPv6 lease? As far as I can see in the dnsmasq man the sorting of IPv4 and IPv6 entries should be the same.

Concerning the flaws: For sufficiently wide screens everything is OK. That upper one can probable be correct, but I'll have to dive deeper into the `<div>`'s... Styling is getting quite complicated there.
I already fixed the table by allowing horizontal scrolling is there is not enough space available.

screenshot at 2016-12-29 18-56-49

**Comment by dschaper** [comment]
IPv6 leases don't use MACs for identification, so I don't know if you'll see them on the wire. They use a (sometimes very long) Device Unique ID (DUID) to identify themselves. It's generated by the client, and is sufficiently random that collisions are highly unlikely. I'll post a screener.

**Comment by dschaper** [comment]
screenshot gimpfrom 2016-12-29 10-03-16

**Comment by dschaper** [comment]
`1483077121 427580664 2001:myprefix::1fd darkrain 00:01:00:01:1d:de:7b:72:50:46:5d:31:55:bd` 

(GitHub likes Germany)

**Comment by darkrain-nl** [comment]
Yeah already changed it in my example ;-)

**Comment by DL6ER** [comment]
So does all lines look like this? I can of course detect if the IP is v4 or v6 and get the correct ordering of the entries

**Comment by dschaper** [comment]
From the RFC

> A DUID consists of a two-octet type code represented in network byte
> order, followed by a variable number of octets that make up the
> actual identifier.  A DUID can be no more than 128 octets long (not
> including the type code).

**Comment by darkrain-nl** [comment]
It's nice to have, but not necessary in my opinion.

**Comment by darkrain-nl** [comment]
Did you revert the scrolling option?
2016-12-29 19_45_40-pi-hole admin console

**Comment by DL6ER** [comment]
No but w/o the MAC it seems to be fitting now for you even without scrolling.

**Comment by darkrain-nl** [comment]
Maybe the lease time in hover?
I think it's nice to have the IP and name besides each other..

**Comment by darkrain-nl** [comment]
Cool now it fits in all cases.

**Comment by darkrain-nl** [comment]
@dschaper MAC go over the line apparently:
`Dec 29 18:31:03 dnsmasq-dhcp[20801]: 10573007 client MAC address: b8:27:eb:8a:56:44`

**Comment by DL6ER** [comment]
I don't analyze the log

**Comment by DL6ER** [comment]
Also we suppress the logging off DHCP actions in the log

**Comment by DL6ER** [comment]
I looked up the format of the lease file in the source code of `dnsmasq` (tho only way to be sure):

1. Time left *or* time stamp of expiration
2. HW address
3. address
4. host name *or* `*` if unknown
5. Client IP *or* `*` if unknown

**Comment by DL6ER** [comment]
untitled3

**Comment by dschaper** [comment]
Looks great, I would lose the Hardware address, it's really only useful to dnsmasq and nobody else, and then modify the ID string to say `DHCP UID:` since that's what the DUID really stands for. (I got it wrong earlier.) But awesome work!

**Comment by DL6ER** [comment]
screenshot at 2016-12-30 00-42-14

There is still some issue on narrow screens...

**Comment by darkrain-nl** [comment]
> I don't analyze the log

I know.

> Also we suppress the logging off DHCP actions in the log

Can this be a setting too? I like logfiles and I use the DHCP log quite often ;-)

**Comment by DL6ER** [comment]
With the more robust log algorithms I have put in and which are merged already we can also enable the logging of DHCP again. 
Should not be too many lines in the end.

**Comment by darkrain-nl** [comment]
Cool!

**Comment by darkrain-nl** [comment]
Looks like HTML is not working in title in Firefox:
2016-12-30 14_36_04-pi-hole admin console

**Comment by darkrain-nl** [comment]
Never mind, now it is working...

**Comment by DL6ER** [comment]
The code in your screenshot was outdated (missing `<br/>`).  `pull` often and clear your Cache even more often (or disable Caching completely like I did)

**Comment by DL6ER** [comment]
Everything should be fine now. The codacy error has to be muted since `DataTables` is like it is (external library) and I cannot change its capitalization.

**Comment by darkrain-nl** [comment]
I have tested the latest commit and I can confirm this all works very nice now.

**Comment by PromoFaux** [comment]
Approved

**Comment by ballsar** [comment]
I would like to see a provision for releasing a DHCP lease.

Thank you

**Comment by DL6ER** [comment]
@ballsar This PR is more than one and a half years old. Please submit feature requests on https://discourse.pi-hole.net instead of in old threads so we can keep track of them and implement then when possible.

**Pull request merged**
