### PR TITLE
Devel Next release

### PR DESCRIPTION
**Pull request by PromoFaux**
DO NOT MERGE

Placeholder for next release. 
@pi-hole/dashboard

### CODE REVIEW

**Comment by PromoFaux** [comment]
I think we still need to check over #108

**Comment by PromoFaux** [comment]
Approved.

**Comment by dschaper** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pi-hole/AdminLTE/pull-request/113/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pi-hole/AdminLTE)

**Comment by Mcat12** [comment]
Approved, because why not? ;)

**Pull request merged**
