### PR TITLE
New logic for API functions getBlockedQueries() and countBlockedQueries()

### PR DESCRIPTION
**Pull request by DL6ER**
Fixes https://github.com/pi-hole/pi-hole/issues/980

Changes proposed in this pull request:

- Simplify and improve `function getBlockedQueries()`

- Simplify `function countBlockedQueries()`

We are currently checking if:
* source is `gravity.list`
* fourth string is *not* `read`
* sixth string is *not* `pi.hole`
* sixth string is *not* `$hostname`

With this PR I want to change that to checking if:
* source is `*gravity.list`
* seventh string is `is`

<pre>
Dec 19 11:40:24 dnsmasq[3072]: query[A] googleads.g.doubleclick.net from 5.6.7.8
Dec 19 11:40:24 dnsmasq[3072]: /etc/pihole/<b>gravity.list</b> googleads.g.doubleclick.net <b>is</b> 1.2.3.4
</pre>

Also we don't have to check any more if `pi.hole` of `$hostname` is there, since those will be feeded by a different list:
<pre>
Dec 19 11:45:30 dnsmasq[3072]: query[A] pi.hole from 5.6.7.8
Dec 19 11:45:30 dnsmasq[3072]: /etc/pihole/<b>hostname.list</b> pi.hole is 1.2.3.4
[...]
Dec 19 11:21:58 dnsmasq[2584]: query[PTR] 1.2.3.4.in-addr.arpa from 127.0.0.1
Dec 19 11:21:58 dnsmasq[2584]: /etc/pihole/<b>hostname.list</b> 1.2.3.4 is pi.hole
</pre>

Note that the old logic might fail on a system with a non-English locale:
```
Dec 19 11:25:14 dnsmasq[3072]: /etc/hosts gelesen - 5 Adressen
Dec 19 11:25:14 dnsmasq[3072]: /etc/pihole/hostname.list gelesen - 2 Adressen
Dec 19 11:25:28 dnsmasq[3072]: /etc/pihole/gravity.list gelesen - 212262 Adressen
```
(there is only "gelesen" but not "read") Luckily, the usual output of `dnsmasq` (like shown above) is still in English.

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
I'll merge this after the current release is out as I'd like to do more testing on `devel` with this changes.

**Comment by DL6ER** [comment]
Gives identical results as the fixed `chronometer.sh`:
```
root@raspberrypi:/etc/.pihole# /opt/pihole/chronometer.sh -j && curl http://pi.hole/admin/api.php?summaryRaw
{"domains_being_blocked":"104449","dns_queries_today":"14314","ads_blocked_today":"304","ads_percentage_today":"2.12"}
{"domains_being_blocked":"104449","dns_queries_today":"14314","ads_blocked_today":"304","ads_percentage_today":"2.1237948861255"}
```

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
