### PR TITLE
Add Verisign Public DNS

### PR DESCRIPTION
**Pull request by YipYup**
Signed-off-by: YipYup

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Add IPv4 and IPv6 public recursive DNS servers from Verisign as upstream server options.

**How does this PR accomplish the above?:**

Adds UI option to select Verisign Public DNS.

**What documentation changes (if any) are needed to support this PR?:**

None needed.

### CODE REVIEW

**Comment by dschaper** [comment]
Sorry, the bot is a bit of a stickler, you can try the instructions at https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project and force push the changes after a rebase if you'd like. But you included the signoff in the PR message so we can overlook the bot in this case as well.

**Comment by YipYup** [comment]
@dschaper Thanks for the info. I'm fine if you'd like to do it from your side. I'm still not actually sure why the bot failed it, unless the regex is overly strict and was looking for a "  <user@domain.tld> " to accompany the Signed-off-by line as well.

**Comment by dschaper** [comment]
The DCO requires a name and email address. The particular bot that we use now does check the name and email against what you have listed as your public name/email on GitHub so it causes problems if you commit with a different name. We'll just bypass the restriction for this run and we're looking at a better DCO enforcement scheme. Thanks for the submission.

**Comment by Mcat12** [comment]
Why should this get added to the web interface over just adding it through the custom DNS option?

**Comment by Mcat12** [comment]
@YipYup Any update on the question and merge conflicts?

**Comment by YipYup** [comment]
You have some good points. All pre-entered DNS server options should be removed.

**Pull request closed without merging**
