### PR TITLE
Add blacklisting and whitelisting features

### PR DESCRIPTION
**Pull request by edward88**
Changes proposed in this pull request:

- add display for blacklisted and whitelisted domains listed on /etc/pihole/blacklist.txt and /etc/pihole/whitelist.txt

- add feature to update whitelist and blacklist domains

- 

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Thanks for the PR, but I'm afraid that there's a few problems. One, to actually cause the lists to update you need to run the whitelist/blacklist command (`pihole -w <domains>` or `pihole -b <domains>`) or gravity (`pihole -g`). These commands require sudo, which is not recommended to give to the web server. Also, we already have list editing. Look in the `whitelist` branch for this (you will need to also install Pi-hole from the `web-sudo` branch on the other repo for it to make the changes).

**Comment by edward88** [comment]
Agreed on the sudo permission should never be given to web server :+1: 
However, it would be helpful to have visibility on the whitelisted and blacklisted domains on the web admin page
Also, the updating of the list may not cause it to take effect immediately but it should take effect after a reboot or service restart. Perhaps adding a statement or clause placed somewhere within the page???

May I know what is the reason for not merging the whitelist branch to the master branch?

**Comment by Mcat12** [comment]
The sudo issue is what's keeping it out. However, we are close in solving it. Actually giving sudo is not the main issue. The `web-sudo` branch gives www-data access to Pi-hole commands. But since we redirect ads to our own webserver, ads could whitelist themselves if there's no authentication. We've come up with a few ways to fix this, including adding a password manually, using http basic authentication, redirecting ads instead to 0.0.0.0, having two webservers running out of different directories/ports, having different IP addresses, and using authentication on the php side to make sure you are whitelisting from the admin page instead of through an ad. We are thinking about testing out the latter, which possibly combined with 0.0.0.0 would be very effective.

**Comment by edward88** [comment]
The solution mentioned is more complex and complete compared to my rather simplistic approach.
Could my request be considered if a statement like "any changes require a reboot to take effect" be added into the page. At least we could get a temporary working list up while the `web-sudo` branch is being developed

In the meantime, I'll check out the `web-sudo` and `whitelist` branch to see if i could contribute to anything :)

**Comment by edward88** [comment]
Updated some minor code re-factoring of changes into single new file in an includes folder.
This is to simplify merging of the `whitelist` branch when it is ready by simply removing 2 files (`list.php` and `includes/blacklist.php`) before merge

I hope this would be considered as it will at least provide general users with visibility and capability _(to some degree)_ of updating the blacklist and whitelist via the admin page

**Comment by Mcat12** [comment]
Sorry, but we will be going with our implementation. Thanks for the effort that you put into this though!

**Pull request closed without merging**
