### PR TITLE
Filter out domains you don't want included in stats

### PR DESCRIPTION
**Pull request by ChadBHowell**
Fixes pi-hole/pi-hole#496 .

Changes proposed in this pull request:

- Add the ability to filter a list of domains from the stats.

@pi-hole/dashboard

Fixes issue pi-hole/pi-hole#496 by @xoniq.  Most code taken from @xoniq in original issue thread.  I moved $filter to global vars at the top for ease of use.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks for the submission! 

Though, I think  [this variable](https://github.com/pi-hole/AdminLTE/pull/136/commits/637fb959cafbfcc0f8d10793332843711fe7b56a#diff-f0cf1ea5c17f50f04b8a0f78860fca46R4) should be read in from a file, something like `/etc/pihole/webUIFilter.conf`, otherwise people would have to go in and change that every time there was an update to the web interface!

**Comment by xoniq** [comment]
I agree on that @PromoFaux .
In my original issue I voted for a solution like that:

> Would be a nice addition to **add my solution to a config section** indeed, where you can **add your own keywords to disable on both domain and hostname** and whatever others want. That would be a more generic solution.

> Then you can tell people to **separate keywords by comma** or something

This is a nice beginning however. Because I am using this currently for a few months, I cannot update using Git since I have an uncommitted change 😁. Good to see some progress on this.

**Comment by PromoFaux** [comment]
I had to double take when I saw this PR, because I recently did something [very similar](https://github.com/pi-hole/AdminLTE/pull/134)!

Actually, whilst I think about it, the title of this PR says domains, but I think perhaps its supposed to be clients?

It's also important that the config does not exist, initially. So (pseudo-code ahead)

```
if (file exists: /etc/pihole/webClientFilter.conf)
    read it in
else
   carry on with no filter
end if
```

My reasoning for this being that some people may actually want results from `127.0.0.1` to be counted in their stats!

**Comment by xoniq** [comment]
Agreed. The filter config should be optional, and just be documented that if you want to hide certain 'domains' like 'localhost' or '127.0.0.1' you have to add them to that file, and the rest will be taken care of by the IF statement and the rest of my filter code.

**Comment by PromoFaux** [comment]
I'll have a tinker about on my lunch break and see what I can come up with. Unless @ChadBHowell get's there before me!

**Comment by xoniq** [comment]
Good to see some progress.
I think this is what should happen:

- Search for config file with filters
- If exists; open config file and get contents
- Get filters from newlines (every filter should be on a new line)
- Implode these filters into 'pipe'-seperated
- Inject full filter combination in current current code as shown in this PR

I think this is basically the fastest and decent way to handle this dynamically.

**Comment by PromoFaux** [comment]
Is the ultimate goal of this to be able to filter out just the clients? Or filter anything at all?

**Comment by xoniq** [comment]
@PromoFaux at first it started at my situation where the statistics were not saying anything at all because I got to many local requests which I really don't care about, I only care about external calls.

It always good to expand it beyond these requirements..

**Comment by PromoFaux** [comment]
OK, so I think what I'd do is have two filters. `/etc/pihole/webClientFilter.conf` and `/etc/pihole/webDomainFilter.conf`, so it's all seperate.

**Comment by PromoFaux** [comment]
Actually, from my fiddling, this is going to require a lot of coffee this evening!

The above solution filters out requests from those clients, but it does not filter out the ads. Which there is no easy way to do without reading the previous log entry. 

image

**Comment by PromoFaux** [comment]
And even then, you can't guarantee that the previous log entry will be the request.

**Comment by ChadBHowell** [comment]
Sorry for the crappy commit message in 83b6042.  Should have read:

Moved client list to /etc/pihole/webClientFilter.conf to be populated one client per line.

(Following is from @xoniq)
1. Search for config file with filters
2. If exists; open config file and get contents
3. Get filters from newlines (every filter should be on a new line)
4. Implode these filters into 'pipe'-seperated
5. Inject full filter combination in current current code as shown in this PR

I believe this commit hips those points.  Some needs to check my coding as I am not real familar with php.

**Comment by PromoFaux** [comment]
The only thing I had to change earlier was adding a semicolon to [this line](https://github.com/pi-hole/AdminLTE/pull/136/commits/83b604208b1003159c0e5f30701f925604eb8e48#diff-f0cf1ea5c17f50f04b8a0f78860fca46L4) Other than that, it's pretty sound!

But see my comments above, whilst this is a nice idea, I think there is going to be more to this than just filtering out clients from the queries. 

When I added ALL my clients earlier, it correctly showed 0 total queries, but the number of ads remained unchanged. Filtering out ad requests from specific clients is not going to be straight forward.

**Comment by ChadBHowell** [comment]
@PromoFaux, you got me on filtering ads from the clients.  Going to need much more coffee to start working on that one...

**Comment by PromoFaux** [comment]
Yeah, It might be possible, but it's a head scratcher! What is annoying is that the reply lines don't necessarily come immediately after the query lines.

```
Sep  8 16:31:32 dnsmasq[577]: reply api.github.com is 192.30.253.116
Sep  8 16:32:19 dnsmasq[577]: query[A] www.google.co.uk from 192.168.216.233
Sep  8 16:32:19 dnsmasq[577]: forwarded www.google.co.uk to 192.168.216.7
Sep  8 16:32:19 dnsmasq[577]: reply www.google.co.uk is 216.58.210.195
Sep  8 16:32:21 dnsmasq[577]: query[A] scontent.xx.fbcdn.net from 192.168.216.233
Sep  8 16:32:21 dnsmasq[577]: forwarded scontent.xx.fbcdn.net to 192.168.216.7
Sep  8 16:32:21 dnsmasq[577]: reply scontent.xx.fbcdn.net is 179.60.192.7
Sep  8 16:32:21 dnsmasq[577]: query[A] www.facebook.com from 192.168.216.233
Sep  8 16:32:21 dnsmasq[577]: forwarded www.facebook.com to 192.168.216.7
Sep  8 16:32:21 dnsmasq[577]: query[A] www.facebook.com from 192.168.216.233
Sep  8 16:32:21 dnsmasq[577]: forwarded www.facebook.com to 192.168.216.7
Sep  8 16:32:21 dnsmasq[577]: reply www.facebook.com is <CNAME>
Sep  8 16:32:21 dnsmasq[577]: reply star-mini.c10r.facebook.com is 179.60.192.36
Sep  8 16:32:22 dnsmasq[577]: query[A] 1-edge-chat.facebook.com from 192.168.216.233
Sep  8 16:32:22 dnsmasq[577]: forwarded 1-edge-chat.facebook.com to 192.168.216.7
Sep  8 16:32:22 dnsmasq[577]: query[A] 1-edge-chat.facebook.com from 192.168.216.233
Sep  8 16:32:22 dnsmasq[577]: forwarded 1-edge-chat.facebook.com to 192.168.216.7
Sep  8 16:32:22 dnsmasq[577]: reply 1-edge-chat.facebook.com is <CNAME>
Sep  8 16:32:22 dnsmasq[577]: reply star.c10r.facebook.com is 179.60.192.3
Sep  8 16:32:22 dnsmasq[577]: query[A] external.xx.fbcdn.net from 192.168.216.233
Sep  8 16:32:22 dnsmasq[577]: forwarded external.xx.fbcdn.net to 192.168.216.7
Sep  8 16:32:22 dnsmasq[577]: reply external.xx.fbcdn.net is <CNAME>
Sep  8 16:32:22 dnsmasq[577]: reply scontent.xx.fbcdn.net is 179.60.192.7
Sep  8 16:32:22 dnsmasq[577]: query[A] video.xx.fbcdn.net from 192.168.216.233
Sep  8 16:32:22 dnsmasq[577]: forwarded video.xx.fbcdn.net to 192.168.216.7
Sep  8 16:32:22 dnsmasq[577]: reply video.xx.fbcdn.net is 179.60.192.15
Sep  8 16:32:30 dnsmasq[577]: query[A] clients4.google.com from 192.168.216.233
Sep  8 16:32:30 dnsmasq[577]: forwarded clients4.google.com to 192.168.216.7
Sep  8 16:32:30 dnsmasq[577]: query[A] clients4.google.com from 192.168.216.233
Sep  8 16:32:30 dnsmasq[577]: forwarded clients4.google.com to 192.168.216.7
Sep  8 16:32:30 dnsmasq[577]: reply clients4.google.com is <CNAME>
Sep  8 16:32:30 dnsmasq[577]: reply clients.l.google.com is 172.217.23.78
```

**Comment by ChadBHowell** [comment]
BTW, my use case for these commits is to filter out request to my sip provider that is inflating the DNS query numbers and throwing off the graphs,

**Comment by ChadBHowell** [comment]
Please correct me if am am seeing this wrong,  The global var $log flows as follows:

1. Call function readInLog()
2. readInLog() reads /var/log/pihole.log line by line into $logData
3. If /etc/pihole/webClientFilter.conf or /etc/pihole/webDomainFilter.conf exists, call function avoidLocalhostEntries($var); if not return $logData as $log
4. avoidLocalhostEntries() loads web*Filter.conf line by line into $filters
5. Strip whitespace from $filters
6. Implode $filters with '|' to $filters_str
7. Use $filters_str to filter $logData and return $logData as $log

The way I see it, $log is filtered before it even reaches getBlockedQueries($log).

**Comment by PromoFaux** [comment]
OK, Lets take the following example:

Say you want to filter client `192.168.1.103` from your results:

```
Sep  8 18:13:49 dnsmasq[15420]: query[A] pixel.facebook.com from 192.168.1.103 <---FILTERED
Sep  8 18:13:49 dnsmasq[15420]: /etc/pihole/gravity.list pixel.facebook.com is 192.168.1.253 <--- STILL COUNTED AS AN AD
```

If that was the entirety of the log, your results would read `1 ad blocked, 0 queries....`

**Comment by PromoFaux** [comment]
I may have just had a brain wave.... If you don't hear from me again tonight, my head has exploded.

**Comment by PromoFaux** [comment]
@ChadBHowell @xoniq Keep an eye on the branch FilterQueries....  I've only gone and done it! There may be a small perfomance cost involved, but I'm no PHP expert.

**Comment by PromoFaux** [comment]
Closing this and opening what I've been working on.

**Pull request closed without merging**
