### PR TITLE
Add custom login page

### PR DESCRIPTION
**Pull request by DL6ER**
Changes proposed in this pull request:

- Add a custom login page

- Display an error if the user enters a wrong password

@pi-hole/dashboard

### CODE REVIEW

**Comment by DL6ER** [comment]
Currently WIP as we are build a new logo for the login page.

**Comment by DL6ER** [comment]
screenshot at 2016-12-13 15-37-57

screenshot at 2016-12-13 15-38-09

**Comment by DL6ER** [comment]
"Forgot password" box is automatically expanded if password is wrong.

screenshot at 2016-12-13 15-40-21

**Comment by Mcat12** [comment]
Add on " by setting an empty password" at the end of the hint on explicitly disabling the password.

**Comment by PromoFaux** [comment]
Testing Github bot

**Comment by PromoFaux** [comment]
Approved, yo.

**Pull request merged**
