### PR TITLE
Add `font-display: swap`.

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [ ] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

### CODE REVIEW

**Comment by DL6ER** [comment]
Note that we never modified stuff in `vendor` directories ourselves. When updating this component, your changes will be overwritten.

It will likely not happen, but I still mention it.

**Comment by XhmikosR** [comment]
How is this a vendor file? What's its source?

**Comment by DL6ER** [comment]
https://github.com/adobe-fonts/source-sans-pro/blob/release/source-sans-pro.css

may have been the source of a former version of this file.

**Comment by XhmikosR** [comment]
https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro

But anyway I doubt anyone will ever need to touch this file...

**Comment by XhmikosR** [comment]
...which reminds me we should actually update the font and add woff/woff2 too

**Comment by XhmikosR** [comment]
Closing this since now I see it's not worth it AFAICT because this CSS file is `import`ed.

**Pull request closed without merging**
