### PR TITLE
Disable text correction features, change types to make input fields easier to type in (especially for mobile devices)

### PR DESCRIPTION
**Pull request by Ghalid**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Some devices/browsers (especially mobile devices) enable spell check, auto correct, auto capitalization, etc on most input fields. For many input fields in the Pi-hole admin interface, this doesn't make sense (such as inputs for domains to whitelist/blacklist), and can make typing them more annoying. This PR disables these features on relevant input fields. Additionally, some input fields are changed to allow mobile users to type in them faster (e.g. an `email` input type has relevant characters, like `@` and `.` available immediately when the keyboard is opened; a `url` input type has `.com` on the keyboard; etc).

**How does this PR accomplish the above?:**

Attributes `autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off"` are added to some input fields. Where domains/URLs are to be inputted, the input type is changed to `url`. Where an administrator email address is to be inputted (in Web/API settings), the type is changed to `email`. Where the DHCP lease time is to be inputted, the type is changed to `number`.

**What documentation changes (if any) are needed to support this PR?:**

None

---

Notes:
- I've tested that these changes have the desired effect as well as some input fields, but not that **all** input fields still work (in theory they should, although additional client input validation from changing the type of an input field may break something; if that's the case it should be changed back to `text`, but I don't believe this is a problem where domains are to be inputted as I was able to add domains through the whitelist with this change)
- ~~It's possible that there may be additional input fields I've missed~~ ~~I've checked and I believe I've changed everything except the search boxes, but I'm not sure how exactly to apply this change to them. I believe it has to do with jQuery, but I don't know much else.~~ Search boxes were fixed. I believe that all relevant text boxes have now been dealt with.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Definitely in favor of this, but can you please make sure you didn't miss any forms?

BTW the Long term data Click to input shouldn't be an input AFAICT. I didn't have the time to tackle this myself

**Comment by Ghalid** [comment]
> Definitely in favor of this, but can you please make sure you didn't miss any forms?

As far as I know from looking back at what I've changed, it seems that the only thing I've missed is the search boxes that appear in places like the Query Log (but as I'm not very familiar with the code I wasn't able to find it quickly, I'll look at it when I have time later).

> BTW the Long term data Click to input shouldn't be an input AFAICT. I didn't have the time to tackle this myself

I think that adding `readonly` to those inputs (which I did in https://github.com/pi-hole/AdminLTE/pull/1100/commits/bf8db707a916ec00e547c3b9bf1cab5d8238a9c2 after reading your comment) should have a desirable effect.

**Comment by XhmikosR** [comment]
But why do those need to be inputs? It seems to me they could just be just
buttons. Maybe split those changes to another PR, I just thought I'd
mention it in case you are interested in tackling this.

**Comment by Ghalid** [comment]
> But why do those need to be inputs? It seems to me they could just be just buttons. Maybe split those changes to another PR, I just thought I'd mention it in case you are interested in tackling this.
> […](#)

Fair enough. Either changing the input type to `button` or just changing it to a `<button>` would probably make more sense (although when I changed `<input>` to `<button>` it ceased to work, while changing the input type to `button` still allowed it to work). I'll make a new PR for this when I can fully figure it out since it I suppose it does stray from the original purpose of this one.

**Comment by XhmikosR** [comment]
I don't see why you need to do it via JS?

**Comment by PromoFaux** [comment]
> text correction for the search boxes with JavaScrip

Is this the search boxes in the data tables?

**Comment by Ghalid** [comment]
> > text correction for the search boxes with JavaScrip
> 
> Is this the search boxes in the data tables?

Yes, I was unable find them in the `php` files.

**Comment by PromoFaux** [comment]
Yeah, I thought that might be the case. The way I have overcome this in the past (on another project) is overriding the default `datatables.net` search box with my own, and then this in the `<script>` part of the page to make it search on enter...

```js
$('#customSearchInput').keyup(function (e) {
            if (e.which == 13) {
                oTable.search($(this).val()).draw();
            }
        });

```

That way the styling could be applied to the custom box.. BUT seems over kill when one could just add it to the native search box.

**Comment by DL6ER** [comment]
How's the status of the code proposed in this pull request? Looking towards the DataTables fields.

**Comment by Ghalid** [comment]
> How's the status of the code proposed in this pull request? Looking towards the DataTables fields.

I've resolved the merge conflicts with the solution I already have in place (I'm not sure whether I should do it another way or not). I didn't have much time to test if there's new DataTables search boxes that I've missed, but I also added the code in question to the groups related pages.

**Comment by Ghalid** [comment]
I tried to change the base branch to `release/v5.0` and resolve merge conflicts but I think I've done some things very wrong

This level of Git is kind of going over my head, ideas/help would be appreciated because I'm not exactly sure how to get back to a good state

**Comment by XhmikosR** [comment]
Just change it back to devel

**Comment by Ghalid** [comment]
Okay, I *think* everything's been resolved with the conflicts and this PR can be tested now.

**Pull request merged**
