### PR TITLE
Removed _fix method from $.AdminLTE.controlSidebar

### LINKED ISSUE #1270: Application unresponsive after resizing the viewport
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---

**Steps to reproduce:**

* Make sure you're using the boxed layout
* Continuously resize your browser for several seconds

**Expected behaviour:**

* The resize operation completes in a timely fashion

**Actual behaviour:**

* The user interface is unresponsive

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`not needed`

**Troubleshooting undertaken, and/or other relevant information:**

About 50 seconds of screen capture:
resize-bug

The performance profile corresponding to the above screen capture (note that each frame takes twice as long to render as the previous):
resize-bug

The bug is cause by a method named ```_fix``` setting an event listener to itself. Every time the browser fires the ```resize``` event, this method is executed and the number of event listeners associated with the resize event is doubled. This causes an exponential increase in CPU time required to handle the resize event and ultimately bombs the browser tab 💣 bye bye 👋

The bug was originally introduced here:
https://github.com/pi-hole/AdminLTE/commit/0fc943905069672bcc77c3301e085da6a083ba80#diff-a31fe31cbbe6a0f5da4bb6b92f5518a4R422

And now exists in minified source here: https://github.com/pi-hole/AdminLTE/blob/master/scripts/vendor/app.min.js#L13

The code that causes the issue, as it exists today, unminified:
```js
    var e = $(".control-sidebar-bg");
    a._fix(e);
    // ------->%-------
    _fix: function (a) {
        var b = this;
        if ($("body").hasClass("layout-boxed")) {
            a.css("position", "absolute");
            a.height($(".wrapper").height());
            $(window).resize(function () {
                b._fix(a);
            })
        } else {
            a.css({
                position: "fixed",
                height: "auto"
            })
        }
    }
```

The purpose of the code is to adjust the height of the background element in the sidebar to match that of a wrapper.

From the perspective of this bug, the most important part of that snippet is on the first line. Everything that follows operates on the ```control-sidebar-bg``` element.

At the point in time where the bug was introduces, there were 29 html files referencing
the ```control-sidebar-bg``` element:
```sh
$ git checkout 0fc943905069672bcc77c3301e085da6a083ba80 > /dev/null
HEAD is now at 0fc94390 Updated light skin logos
$ git grep -ol control-sidebar-bg | grep html | wc -l
      29
```

Now there are 0:
```sh
$ git checkout devel > /dev/null
Switched to branch 'devel'
$ git grep -ol control-sidebar-bg | grep html | wc -l
       0
```

### In conclusion

1. The entire code snippet pasted above must be removed from the code base, as it references a non-existing element and introduces a bug as per above.

2. There is further dead code referencing the ```control-sidebar-bg``` element a css file, but that's just bloat, doesn't break anything and can be left alone.

If the offending code is removed from the code base, there are no visible side effects. The user interface no longer become unresponsive following a resize operation and each frame now takes about the same amount of time to be rendered:

Screenshot 2020-05-12 at 11 09 35

### PR DESCRIPTION
**Pull request by roccivic**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fixes #1270

**How does this PR accomplish the above?:**

See #1270 

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by PromoFaux** [comment]
I'm a little uneasy with modifying the vendor file directly within this repo. Although it is unlikely that we will update to a newer version of AdminLTE (see https://github.com/pi-hole/web - there is no planned timeframe for this at the moment), so we're unlikely to lose the changes made here.

I wonder if the same thing could be achieved with some kind of override/patch in an external file? Just spitballing, my `js` knowledge is limited at best!

This repo originally started out as a fork of the AdminLTE template repository, when probably it should have just started from scratch and used the library instead.

**Comment by roccivic** [comment]
The last version of AdminLTE that contains this bug is 2.3.11: https://github.com/ColorlibHQ/AdminLTE/blob/2be703222af2edcb87e562d3da2299e4352bff8a/dist/js/app.js#L518

That whole section of code got a re-write and the issue is clearly no longer there: https://github.com/ColorlibHQ/AdminLTE/blob/6157c7bc77bfca7e9aa75f529f3f612122d9a2f1/dist/js/adminlte.js#L362

Just make a note of upgrading at least to 2.4.0 when the time comes.

Besides that, I don't know what to suggest.

**Comment by PromoFaux** [comment]
2.4.x Might be the way to go, it is more compatible with 2.1 than 3.x is!

But having tried both your change and dropping in v 2.4, I can see that it is indeed a vast improvement on responsiveness. Unfortunately there are a few changes that need to be made elsewhere in the code to update it to 2.4, I will try to work on that if I find time later on today.

It seems to be only where we are calling for `$.AdminLTE.options.colors` in `index.js`

Ofcourse, feel free to make a PR with an update of the library to 2.4 if you wish/can beat me to it :)

**Comment by roccivic** [comment]
superseeded by #1272

**Pull request closed without merging**
