### PR TITLE
Rewrite in Angular JS

### PR DESCRIPTION
**Pull request by brantje**
Changes proposed in this pull request:

- Complete rewrite to Angular JS

@pi-hole/dashboard

### CODE REVIEW

**Comment by brantje** [comment]
Will dump the bower_components folder this evening.

**Comment by brantje** [comment]
To do list
[ ] Remove bower_components
[ ] Incoperate https://github.com/pi-hole/AdminLTE/pull/106
[ ] Remove unneeded fonts

Am i missing something @dschaper ?

**Comment by dschaper** [comment]
So far that all looks good. Just for something to keep in mind, Flask is most likely going to be the framework we deploy on...

**Comment by brantje** [comment]
An optional idea is a nice blue loading spinner, that waits till the dashboard is fully loaded.
An additional option here is to wait till all data is received.
Let me know what you think of this.

**Comment by Mcat12** [comment]
This is targeting master from master... Before we merge, it needs to be targeting devel from preferably devel.

**Comment by brantje** [comment]
Will submit a new PR targeting devel.

**Pull request closed without merging**
