### PR TITLE
Add Meta Tags and Images

### PR DESCRIPTION
**Pull request by slamanna212**
Added Fav icons for desktop and mobile platforms and theme color for mobile browsers

**Example of Theme Color:**

Colored Nav Bar

**Example of Icon in Chrome on Android:**

Android Icon

### CODE REVIEW

**Comment by Mcat12** [comment]
Does it need that many pictures?

**Comment by slamanna212** [comment]
When i created the Favicon it gave me that many. I looked them up and, depending on what the device supports , it will load a higher resolution image. Without the higher resolution ones, it will look poor on High res screens. Without the low res ones, it wont work on some devices.

All of those image files are only 668K, so it isnt a lot of disk space being taken up

**Comment by Mcat12** [comment]
Can it scale the high res?

**Comment by slamanna212** [comment]
Im not sure what you are asking. Can the lower resolution devices scale
down the higher res file?

**Comment by PromoFaux** [comment]
As far as I'm aware, high resolution icons will be scaled down by the client browser

**Comment by slamanna212** [comment]
Interesting, I have never heard an answer one way or the other. If so, i could remove a bunch of the files and lines of code, il do that

**Comment by PromoFaux** [comment]
Try it out on your local copy! Leave the largest one in the folder, and delete the rest. :)

**Comment by slamanna212** [comment]
Was unable to test an iDevice but they worked on PC and on Android, i updated my commit by removing the un needed  <meta> tags and un needed files!

**Comment by slamanna212** [comment]
Ok, fully tested changes, all working , all files that should be there are, nothing more.

**Comment by Mcat12** [comment]
What kind of apps work with this? Chrome does not seem to do it.

**Comment by slamanna212** [comment]
My code adds the theme colors in the screenshots for android devices 5.0+ and the icons are for idevices, android devices and microsoft devices. It also adds a favicon to desktop browsers

**Comment by slamanna212** [comment]
For chrome desktop , this is all it does:

favicon example

**Comment by Mcat12** [comment]
I'm on Android 6.0 and don't see it with chrome... And I thought we had a favicon, but whatever.

**Comment by PromoFaux** [comment]
Tested this on my Nexus 6p. Works fine!

With:
image

Without:
image

**Pull request merged**
