### PR TITLE
Rewrite Top Items computation

### LINKED ISSUE #294: UI shows no temp, Top Domains and Top Advertisers are mashed up.
After update my pi-hole don't show temp in UI ,it shows 0. I'm running it on Orange Pi with Armbian. Sometimes seems that results in Top Domains and Top Advertisers are mashed up.

[https://streamable.com/kx9ib](https://streamable.com/kx9ib)

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---
Fixes #294

Rewrite of Top Items algorithm to use the same mechanism as Query Log to determine whether a domain in an Ad domain or not (use Gravity information instead of processing `pihole.log`).

- http://pi.hole/admin/api.php?topItems gives (up to) 10 Top Item entries (both Domains and Ads)

Additional feature for the API:
- http://pi.hole/admin/api.php?topItems=X gives (up to) X Top Item entries (both Domains and Ads)

Speed comparison for Top Items: Almost no change with 18101 total DNS queries.
- previously (`devel`): 1.6s
- now (this branch): 1.5s 
For a very low number of DNS queries the old mechanism can be faster. For an even higher number of total DNS queries, the new scheme will always be faster.

Speed comparison for Main graph (`getOverTimeData10mins`): Almost no change with 18101 total DNS queries.
- previously (`devel`): 2.7s
- now (this branch): 2.9s

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Not fully looked into this yet, but getting the following errors on this  branch:

```
2017-01-01 20:07:56: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Missing argument 2 for overTime10mins(), called in /var/www/html/admin/scripts/pi-hole/php/data.php on line 94 and defined in /var/www/html/admin/scripts/pi-hole/php/data.php on line 616
2017-01-01 20:07:56: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined variable: ads_blocked in /var/www/html/admin/scripts/pi-hole/php/data.php on line 95
2017-01-01 20:07:56: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Missing argument 2 for overTime10mins(), called in /var/www/html/admin/scripts/pi-hole/php/data.php on line 95 and defined in /var/www/html/admin/scripts/pi-hole/php/data.php on line 616
2017-01-01 20:07:56: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/admin/scripts/pi-hole/php/data.php on line 619
2017-01-01 20:07:56: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined variable: ads_blocked in /var/www/html/admin/scripts/pi-hole/php/data.php on line 99
```

**Comment by DL6ER** [comment]
@PromoFaux Check again.

**Comment by PromoFaux** [comment]
image

**Comment by DL6ER** [comment]
You are not up-to-date. The variable `$ads_blocked` in your error log does not exist any longer.

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
