### PR TITLE
Advanced stats and graphs

### PR DESCRIPTION
**Pull request by bricej13**
#### Added the following UI elements:
- A graph of queries over time
- Top chart of valid queries
- Top chart of advertisement queries
- Chart of most recent queries

#### Architecture changes
- sed/awk/wc replaced with PHP
- Moved data generation to separate file data.php file
- Data.php is used both in index.html and api.php

screen shot 2016-01-25 at 9 29 18 pm

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks for the submission! We'll have the web development team take a look at that. Looks like there's some merge conflicts we need to clean up though.

**Comment by PromoFaux** [comment]
I'll take a look a the conflicts later on. I like the idea of moving the API calculations back into PHP, I only moved them out to `chronometer.sh` before as my PHP skills... lack finesse. (To be fair, so do by bash skills.. but that's not the point!)

**Comment by bricej13** [comment]
I couldn't tell you whether the PHP is faster than the Bash scripts. It does, however, make it easier to build the advanced statistics.

**Comment by PromoFaux** [comment]
I think I prefer the idea of doing the API in PHP, one of the other reasons I moved it to `chronometer.sh -j` was that `chronometer.sh` was doing those calculations anyway, and as it stood at the time, `api.php` and `chronometer.sh` had different results :)

The master branch has been updated a bit since you originally forked, so it might be an idea to resolve any conflicts by merging the master back into your branch.. perhaps even rebasing on the current devel branch. @jacobsalmela wont be as active for a little bit, but @Mcat12 knows his way around the repo if you have any questions.

**Comment by bricej13** [comment]
Fair enough. I'll look into doing that when I can find the time.

**Comment by Mcat12** [comment]
Right now, master is very behind on code. We were about to push the new code from devel (the dev branch) to master, but need to fix up some things first. It would be very helpful if you could update your fork and rebase your work onto devel, or even make a new branch off of devel and make your changes there.

**Pull request closed without merging**
