### PR TITLE
Feature/top limits

### PR DESCRIPTION
**Pull request by agomezxff**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

I was thinking that allowing to get more results than 10 in Top LIst would be useful

**How does this PR accomplish the above?:**

- Changes in UI
- Changes in the DB API queries and a new $_GET param

**What documentation changes (if any) are needed to support this PR?:**

`{A detailed list of any necessary changes}`

> * `{Please delete this quoted section when opening your pull request}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand an issue quicker, but please ensure it's relevant.

This is my first contrib on github. Hope it's well done!

### CODE REVIEW

**Comment by agomezxff** [comment]
Allowing users to set the limit of Top Lists

**Comment by Mcat12** [comment]
This web interface is going to be replaced with the [new web interface] and [API]. New features should be implemented there, otherwise they would have to be implemented twice (in this web interface and in the new one).

If we do add customizable limits for top lists, it should be implemented such that it is a setting in the web interface which can be adjusted for all top domain/client lists and across user sessions.

[new web interface]: https://github.com/pi-hole/web
[API]: https://github.com/pi-hole/api

**Comment by agomezxff** [comment]
I think that a GET param in API/UI would be also useful in the case users want to make a punctual query on "long term data/top lists" with more results ie.200, and not overloading the main dashboard with such big data

**Comment by Mcat12** [comment]
In the new web interface, the long term data is viewed in the same way as the normal last 24 hours data (there is no special long term data page). The dashboard and query log can be used to view any range of data. Any features added to the dashboard applies to any range of data (normal and long term). In this setup, changing the limit of the top lists applies to the dashboard.

Now there is very little difference between changing the limit as a one-off action vs changing it in the settings. For the one-off action, would that be a per-session override or only for that page refresh? Also, from a UX perspective, how should the override be input? It should be general enough so that future filters could be added, and it should not be intrusive on the page (should not take up space with an input and button like in this PR if the user is not actively using that feature).

There are a lot of design questions that have to be answered before this can be added. The design should be extendable and fit within the rest of the web interface.

**Comment by agomezxff** [comment]
Probably I didnt explain well the utility of this change. I agree a dashboard doesn't is supposed to have a lot of inputs plenty of data. In the old UI there was the long term data that was the place where I made the changes.

I think in term of use, an independent page for this kind of new options for stats, where other options could be set (such as query over a domain, this limit option) where the API data apply that rules and the UI view present the same info (graphs, lists -where agregated values(MIN, MAX) could be added-) than in dashboard only with the filtered data.

But it is far beyond what I meant it. As the API is, the limit option can be implemented just sending the limit value in the query string of the ajax calls. And in the html, a collapsible data set can be added as the "advanced search" of any seach-engine. All the inputs can be included in a html form, and the ajax calls would be set to include the whole form serialized or whatever, and future new input fields would be sent.

Said so, is the first time I contrib in github and as I would be barely able to make the changes in the new project by myself as I have never worked in react nor any other ts, I don't know if this PR would have to be moved as a feature request of the new project or if this PR can be merged meanwhile the new api/web is released for dist

**Comment by Mcat12** [comment]
> I think in term of use, an independent page for this kind of new options for stats, where other options could be set (such as query over a domain, this limit option) where the API data apply that rules and the UI view present the same info (graphs, lists -where aggregated values(MIN/MAX-first/last query datetime) could be added-) than in dashboard but with the filtered API data.

Can you clarify this? It does not sound like you finished your thought here.

The web interface uses pre-defined queries to display various data, and (in the new web interface) can filter the query log along the columns provided. Further query analysis can be done through SQL by connecting to the database, or by forwarding the data to a service such as Splunk or InfluxDB + Grafana.

**Comment by agomezxff** [comment]
Something like this:

proto

**Comment by Mcat12** [comment]
Please open a feature request in Discourse for this. Thank you for the effort you put into this, we appreciate it.

**Pull request closed without merging**
