### PR TITLE
Fix arrow positions in sidebar to be vertically centered

### PR DESCRIPTION
**Pull request by eddturtle**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

1 {replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
_{replace this line with your pull request content}_

Fix arrows in sidebar.
Before: https://www.dropbox.com/s/icme2dvclb6fv1m/pihole-before.png?dl=0
After: https://www.dropbox.com/s/osjnj1ldnwvjhkj/pihole-after.png?dl=0

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Because you based your branch off `master`, you didn't have the Long Term Data arrow and didn't fix that one. I merged `devel` into your branch, so you should have the up to date code (including that third folder which needs to be fixed like the other two).

**Comment by eddturtle** [comment]
Thanks for looking at this and doing the merging I think I got my branches mixed up. I've fixed the extra button on the devel branch.

**Comment by PromoFaux** [comment]
Approved

**Comment by Mcat12** [comment]
Changing to the release branch as this is a bugfix.

**Pull request merged**
