### PR TITLE
Update wording on main page

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
image

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Th3M3** [comment]
Today I've switched my pi-hole to the devel branch.

Now the boxes have different hights, like you see on my screenshot
Is this wanted?

boxes

**Comment by PromoFaux** [comment]
Ah, good catch. Are you in boxed layout? That's one thing I didn't check!

**Comment by Th3M3** [comment]
I don't use the boxed layout.
My [viewport size](http://viewportsizes.com/mine/) is 1280×621px.
(I am using a laptop with FullHD-Display (1920x1080px) and a scale factor set in windows at 1.5, because the screen size is only 13")

**Comment by PromoFaux** [comment]
Hmm, OK. It's much wordier than the old text. I'll see if I can think of something a bit more succinct.

**Comment by Th3M3** [comment]
Or what about leaving the wording as it is and add an extra css media query for viewport widths between 1200px and 1600px?
For testing I have changed the boxes width with my Browser's Developer-Tools to 50% instead of 25%.

So it would look like this:
boxes_new

But I don't know how to change this in AdminLTE. It looks like it is written in LESS and I have never worked with it.

**Comment by dschaper** [comment]
`DNS Queries Blocked Over Last 24 Hours` == `Queries Blocked Last 24 Hours`
`DNS Queries Over Last 24 Hours` == `Queries Last 24 Hours`
`Queries Were Blocked Over Last 24 Hours` == `Queries Blocked Last 24 Hours`
`Domains Being Blocked` == `Domains Blocked`

**Comment by Th3M3** [comment]
Yes, this works too.
boxes_new2

**Comment by dschaper** [comment]
The one that I'm concerned about is `Domains Blocked` and if that can be viewed as a total of blocks over a large time period. How about `Domains on Blocklists`?

**Comment by Th3M3** [comment]
`Domains on Blocklists` describes it better and also fits in one line.

**Pull request merged**
