### PR TITLE
Deleted Ionicons as dependency. Changed existing usage to fontawesome…

### PR DESCRIPTION
**Pull request by Pazekal90**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Deleted a dependency ionicons to get better performance in browser and less doubled icon libraries. 

i have changed the existing ion icons to fortawesome icons.

### CODE REVIEW

**Comment by Mcat12** [comment]
Can you change the icons to be closer to their originals? See the icons used in the React web interface: https://github.com/pi-hole/web/blob/3b5240e32a0e80794a3c1813036d9098f3f0194a/src/components/dashboard/SummaryStats.tsx#L65

http://web.pi-hole.net/

**Comment by Pazekal90** [comment]
> Can you change the icons to be closer to their originals? See the icons used in the React web interface: https://github.com/pi-hole/web/blob/3b5240e32a0e80794a3c1813036d9098f3f0194a/src/components/dashboard/SummaryStats.tsx#L65
> 
> http://web.pi-hole.net/

Sure! Done.

**Comment by Pazekal90** [comment]
Sorry but I edited those lines in GitHub directly with no sign-off. Can you merge either way or how can i reverse sign-off my commits.

**Comment by Mcat12** [comment]
The DCO bot has some instructions for you here:
https://github.com/pi-hole/AdminLTE/pull/1023/checks?check_run_id=272335666

**Pull request merged**
