### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Changes proposed in this pull request:

- modify div's with display to use HTML span elements

- allows footer to get correct AdminLTE version, even if not at `/var/www/html/`

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
It looks like something happened to your branch (You have some commits that shouldn't be there). You should start a new branch based off of dev and either cherrypick the changes or do them again. Then open a new PR. (Sorry :cry:)

**Comment by dschaper** [comment]
Just looks like the readme.md is an old version. The rest looks okay?

**Comment by Mcat12** [comment]
If we merge in the merge commits, the version on the dev branch will show as something besides `vDev`.

**Comment by dschaper** [comment]
I'm missing something... (Not surprising, I know...)

**Comment by Lewiscowles1986** [comment]
@Mcat12 all edits when I click the PR are edits I intentionally made; none affect the operation of the SW and do make it more correct in terms of HTML, and able to cope with change (the removal of cd && command prefix)

**Pull request closed without merging**
