### PR TITLE
Pi-hole Web Admin v2.5

### PR DESCRIPTION
**Pull request by PromoFaux**
Release

### CODE REVIEW

**Comment by DL6ER** [comment]
Approved

**Comment by DL6ER** [comment]
Approved

**Comment by dschaper** [comment]
Approved

**Comment by DL6ER** [comment]
Approved

**Comment by dschaper** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by DL6ER** [comment]
Changed title to `[WIP]` in order to prevent releasing w/o bugfix https://github.com/pi-hole/AdminLTE/pull/421

**Comment by DL6ER** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by dschaper** [comment]
Approved (again?)

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
