### PR TITLE
Add privacy mode

### PR DESCRIPTION
**Pull request by DL6ER**
See https://discourse.pi-hole.net/t/privacy-mode-anonymize-logs/797/6

Changes proposed in this pull request:

- Add privacy mode (permitted queries are not shown any longer)

@pi-hole/dashboard

### CODE REVIEW

**Comment by PromoFaux** [comment]
@DL6ER Does this have a paired PR on the core repo to add the

**Comment by PromoFaux** [comment]
The info box suggests that all entries will be shown in the query log regardless of wether this setting is toggled or not.

image

**Comment by DL6ER** [comment]
@PromoFaux I fixed that.

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
Waiting for codacy

**Pull request merged**
