### PR TITLE
Update year 2017 -> 2019

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Update year in comments

**How does this PR accomplish the above?:**

```
sed -i "s/(c) 2017/(c) 2019/g;" *.php
```

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by PromoFaux** [comment]
Is there something that we could do to make it `(c) 2017 - ${currentYear}` ?

**Comment by DL6ER** [comment]
They are comments in the code not like PHP or anything that can be dynamic.

**Comment by dschaper** [comment]
Technically it's just a nicety to have the dates updated, we won't lose the copyright if the date doesn't update. Just the date of first publication is enough. 

See https://stackoverflow.com/a/2391555 for a few views on the topic.

**Comment by DL6ER** [comment]
Closing as I seems I slightly misunderstood the topic

**Pull request closed without merging**
