### PR TITLE
Add 'Top Clients' name resolution from hosts file

### PR DESCRIPTION
**Pull request by atesca09**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 1

---
Adds the client name resolution from the queries page to the index page 'Top Clients' list aswell

### CODE REVIEW

**Comment by Mcat12** [comment]
Top Clients should already reverse lookup the hostnames from `/etc/hosts` if you check the setting in the settings page.

**Comment by Mcat12** [comment]
@atesca09 Does this PR do something new?

**Comment by atesca09** [comment]
I was looking for the resolve client names option and couldnt find it :(

With this PR the Top Clients are displayed in the same format as on the Queries Log page ( <name>(<ip))
But I'd recommend closing this PR and changing the format in the requestIPs function

**Comment by DL6ER** [comment]
When you enable `API_GET_CLIENT_HOSTNAME`, than the function `resolveIPs` will exactly do that (resolve the IPs to hostnames). This resolution includes all data that the Pi-hole knows from its `/etc/hosts` file.

This data is formatted like `hostname@IP` and parsed by the JS script to show only `hostname`. Do I understand this correctly, that you would rather like to see `hostname(IP)?`. This will be a very long string and probably don't fit well into the tables.

**Comment by DL6ER** [comment]
@atesca09 Please have a look at #346

**Comment by atesca09** [comment]
It helps a bit, but I still prefer the hostname(IP) format like it is on the query log pages

**Comment by DL6ER** [comment]
We decided to get rid of that because of the table looking really bad for people using IPv6 in their internal network. It is no problem for a line like:
```
somehost.local(192.168.1.10)
```
However,
```
android-db4fb31512299e9971cfbc75cc60ca628861d3f5(fe80:0000:0000:0000:0000:0000:c0a8:010a)
```
is certainly a problem.

**Pull request closed without merging**
