### PR TITLE
tabs for new domain/regex input

### PR DESCRIPTION
**Pull request by Th3M3**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

improve behavior for adding new domains and regex filters

**How does this PR accomplish the above?:**

- add separate tabs for adding regular domains or regex filters.
- replace _type_ dropdown box and _Add_ button with buttons _Add to blacklist_ and _Add to whitelist_ for faster interacting
- corresponding semantics in messages when adding/editing/removing domains or regex filters.

add_new

**What documentation changes (if any) are needed to support this PR?:**

may needed after merging `domain_regex_input` into `release/v5.0`

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/rename-wildcard-blacklist-whitelist-because-it-is-misleading-and-lead-to-regex-errors/28867/80

**Comment by Th3M3** [comment]
BTW: I saw a missing space character while testing/adding `bad_domain.com` to exact whilte/blacklist):


This is not due to this files and needs to be fixed somewhere else. 
I had no closer look at this so far.

**Comment by DL6ER** [comment]
@Th3M3 Thanks for pointing this out. I've seen it as well a few days ago and I'm pretty sue one of my open PRs already addresses this.

**Comment by DL6ER** [comment]
@Th3M3 Sorry for another ping but I just wanted to mention that I will set DCO to pass manually as you included a proper Sign-Off (just not the one DCO expected).

**Comment by Th3M3** [comment]
> ... I will set DCO to pass manually as you included a proper Sign-Off (just not the one DCO expected).

Thanks @DL6ER. I am working with _Github Desktop_ software for windows, wich sadly does not offer a proper a `--signoff` equivalent.

This time I saw what DCO expected in my `signed-off` line.
I will enter the line as per DCO's expection next time.

**Pull request merged**
