### PR TITLE
Issue#983

### PR DESCRIPTION
**Pull request by denny0754**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**
Fixes Issue[#983 ](https://github.com/pi-hole/AdminLTE/issues/983)

`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`
Before:
before
After:
after
**What documentation changes (if any) are needed to support this PR?:**
N/A

### CODE REVIEW

**Comment by Mcat12** [comment]
Please rebase your branch off of development.

**Comment by PromoFaux** [comment]
@denny0754 I have ammended your PR to be based on the `devel` branch as per contribution guidelines.

Rather than get you to do it all over again, I did the following:

```
git clone git@github.com:denny0754 /AdminLTE.git
cd pi-hole
git checkout devel
git checkout -b denny0754 #this creates a new local branch on my workstation called denny0754 
git cherry-pick 8991605 #This adds a copy of your commit onto this fresh new version of mybranch
git push origin denny0754 --force #This was a bit naughty, but it essentially overwrites mybranch on the remote with the version that I just created.
```

(If you're wondering how I was able to push to your fork... when you open a pull request to the original repo, it allows people with write access to the original repo to push to your fork's branch)

Please review the status of the [DCO bot](https://github.com/pi-hole/AdminLTE/pull/984/checks?check_run_id=183222660) and action accordingly to make it happy!  We have a [guide here](https://docs.pi-hole.net/guides/github/how-to-signoff/) if you need pointers on that. 

If you are not comfortable with redoing the commit and adding the signoff, then you can just add the signoff lines in a comment here along the following (Change out the name/email for your own!):

```
Signed-off-by: Random J Developer <random@developer.example.org>
```

**Comment by denny0754** [comment]
I tried to follow what the DCO Bot told me, which is:
```git commit --amend --signoff```
and
```git push --force-with-lease origin denny0754```
while it does let me signoff the commit, I can't push, even if a force it as told by the bot.
I rather give you my signoff here:

```Signed-off-by: Diego Vaccher <diego@vaccherdiego.it>```

**Comment by PromoFaux** [comment]
That may be due to how I corrected the PR. Not to worry, happy to accept the signoff in the comment, and will manually override the DCO bot on this occasion.

Thanks for the submission!

**Comment by dschaper** [comment]
Thanks for the submission!

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-4-3-2-release-notes/23852/1

**Pull request merged**
