### PR TITLE
open external links in new window

### PR DESCRIPTION
**Pull request by TylonHH**
@pi-hole/dashboard

external links should be open in a new window

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved (Update branch from devel please)

**Comment by PromoFaux** [comment]
@TylonHH Could you redo these changed from the `devel` branch instead? It will be easier than sorting out the merge conflicts!

**Comment by dschaper** [comment]
Is this just the one commit? I may be able to cherry pick that into a PR that works on the updated code if we need to, but I'll let TylonHH take a stab at it first. Love me some Merge Conflicts!

**Comment by TylonHH** [comment]
Sorry, I don't wanna make trouble.
It's my first commit ever, I wanna learn how to help here. I also edited the readme because of outdated command.
It's no big deal, i hope

**Comment by PromoFaux** [comment]
Certainly dont want to put you off contributing! 

Basically the rule here is that you make your changes based off of the development branch, and make pull requests to that branch too, as it is often ahead of the master branch!

I spotted the wiki changes the other day, thanks for that! The formatting may need a bit of tidying up just to make it easier to read, but good job!

**Comment by dschaper** [comment]
Not a big deal at all, great way to learn the process. Normally everything goes smooth, but sometimes you edit a line of code that has been edited by antother PR or commit already and Git doesn't know which commit should be applied, and that leads to a merge conflict. Happens to all of us, and GitHub actually does a pretty good job walking you through a conflict resolution. Thanks for the contributions, and welcome to git! ;)

**Pull request closed without merging**
