### PR TITLE
Allow multiple upstream DNS servers (incl. IPv6)

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

- Allow multiple upstream DNS servers
screenshot at 2017-01-13 17-50-19

- Allow IPv6 addresses in the exclude filter

After reading the `dnsmasq` code a bit more I figured out that this will not drastically increase the used bandwidth (as I though initially). `dnsmasq` will send queries to any of the upstream servers that are enabled and tries to favor servers that are known to be up (favor = the fastest to respond). Only if this favorite server fails to answer, `dnsmasq` will reach out to the others. It will occasionally send a query to all of them to identify if the favored server is still the best choice.

Core changes: https://github.com/pi-hole/pi-hole/pull/1135

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by darkrain-nl** [comment]
2017-01-14 14_13_20-pi-hole admin console
2017-01-14 14_13_25-pi-hole admin console
2017-01-14 14_13_29-pi-hole admin console
2017-01-14 14_13_34-pi-hole admin console
Just to give an idea how much each server gets to do...
I run a config like this for some time already, 6 or 7 months, without any problems.
So good thing to add.

**Comment by DL6ER** [comment]
screenshot at 2017-01-14 15-30-30

With all 10 enabled. Level3 is slightly preferred by `dnsmasq` it seems. Still, the time interval in between which `dnsmasq` check for the fastes is quote short and the "favored" server changed frequently in my setup.

**Comment by davekr8** [comment]
An option to use the `all-servers` flag of dnsmasq would be nice. From my point of view it changes the way the servers is accessed. With the flag, there seems to be parallel requests, with the first reply being used for forwarding. This might be a option to control number of dns requests vs. minimum latency. Maybe worth a small feature request ?!

Just my 2 ct.

**Pull request merged**
