### PR TITLE
Updated Dependency font-awesome 5.6.3 => 5.11.2

### PR DESCRIPTION
**Pull request by Pazekal90**
Signed-off-by: Pazekal90 <mail@pascal-pischel.de>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Updated the dependency Font-Awesome to the latest version and tested it. No Errors.

### CODE REVIEW

**Comment by DL6ER** [comment]
Could you provide a changelog for what happened between these two releases that night be interesting for us?

**Comment by Pazekal90** [comment]
Changelog for the changed 5.6.3 => 5.11.2. 

The most interesting changes marked in italic.
But: I think software should stay up to date with their assets even there are no "super new" features. Investigating a bug in safari version xy is way more time-expensive than keeping assets up to date.

## [5.11.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.11.2) - 2019-09-23

### Changed
* Updated laravel brand icon

### Fixed
* New scanner-image icon was using the same unicode value as scanner causing overlapped icons
* The film-canister icon was incorrectly spelled film-cannister

---

## [5.11.1](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.11.1) - 2019-09-18

### Fixed
* Duotone icons updated in 5.11.0 had incorrect attribute order which caused
  them to fail to load for all kits

---

## [5.11.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.11.0) - 2019-09-18

### Added
* New tech, music, and western-themed icons
* Added umbraco, swift, orcid, mdb (and one more surprise) brand icons

### Fixed
* SVG with JavaScript no longer duplicates the id attribute when in nesting mode
* Corrected inconsistencies with the send-back and send-backward icons
* Corrected inconsistencies with duotone icon viewBox widths that did not match
  the solid style

---

## [5.10.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.10.2) - 2019-08-22

### Added
* SVG with JS API function layers() now accepts params to add additional classes

### Changed
* Lots of updates to various duotone icons
* Updated the keybase brand icon

### Fixed
* Duotone icon updates FortAwesome/Font-Awesome#15396
  FortAwesome/Font-Awesome#15409 FortAwesome/Font-Awesome#15413
  FortAwesome/Font-Awesome#15325 FortAwesome/Font-Awesome#15334
  FortAwesome/Font-Awesome#15339 FortAwesome/Font-Awesome#15346

---

## [5.10.1](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.10.1) - 2019-08-02

### Added
* README file in the otfs/ directory to help direct folks to documentation for the new Duotone OTF file

### Changed
_* A lot of visual improvements and consistency fixes to many of the new Duotone icons_
* The fa-swap-opacity class now works with parent containers where Duotone icons as children

### Fixed
* Duotone SCSS files were not being correctly compiled with the Dart-Sass tool
* Font Awesome logo was not appearing in desktop application in font pickers

---

## [5.10.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.10.0) - 2019-07-29

### Added
* Duotone icons style added with over 1,600 new icons
* New conflict detection script to help identify conflicting versions of Font Awesome (js/conflict-detection.js)
* Icons border-center-v and border-center-h
* New brand icon for cotton-bureau

### Changed
* Updated version 4 shim to more accurately match sort-alpha-desc, sort-amount-desc, sort-numeric-desc

### Fixed
* Icon sort-amount-down-alt incorrectly matching sort-amount-down
* Icon border-outer icon missing inner grid shapes

---

## [5.9.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.9.0) - 2019-06-04

**Minor version upgrade notice: there are some backward-incompatible changes to this release. See the
[UPGRADING.md guide](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md) for more
information.**

### Added
* An assortment of voted icons, updated icons, and new icons
* New icons and updates to the text editor category
* A flipped version of the phone and phone-alt icon

### Changed
* Removed the nintendo-switch icon by request of Nintendo
* Sorted out the sort icons FortAwesome/Font-Awesome#9464 FortAwesome/Font-Awesome#9419 FortAwesome/Font-Awesome-Pro#915
* De-crevassed the brain icons

### Fixed
* Proportions corrected on facebook-messenger brand icon

---

## [5.8.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.2) - 2019-05-07

### Added
* New brand icon stackpath

### Changed
* Updated redhat, mailchimp brand icons
* Updated Facebook brand icons in accordance with https://facebookbrand.com (facebook, facebook-f, facebook-square)
* Updated Git brand icons (git, git-square, git-alt)
* Removing the "at" character to prevent overlap with the at icon

### Fixed
* Missing version for the route icon FortAwesome/Font-Awesome#13804
* Corrected the orientation of radiation and radiation-alt icons
* Alignment fixed for check-double
* Moved the notch into the correct location for sim-card
* Allow the role attribute to be specified FortAwesome/Font-Awesome#14791
_* Prevent IE11 CSS selector error from crashing SVG with JS execution_

---

## [5.8.1](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.1) - 2019-03-21

### Fixed
* Correct the baseline alignment of the linkedin-in brand icon

---

## [5.8.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.0) - 2019-03-20

**Minor version upgrade notice: there are some backward-incompatible changes to this release. See the
[UPGRADING.md guide](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md) for more
information.**

### Added
* New sponsored icon wave-square
* Adding new mutateApproach configuration which can force SVG with JS to render synchronously
* Adding a round of top requested brand icons

### Changed
* Updating search terms and adding new categories
* Removing descender-based CSS from the .fa-icon Sass mixin
* Removed title elements from SVG sprites

### Fixed
* Fixing several icons such as spinner-third that had incorrect widths
* Allow Sass setting for `font-display` to be changed
* Missing dots in the flower icons
* Support strict math compatibility for Less
* Support fa-flip-both in the SVG with JS version

---

## [5.7.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.7.2) - 2019-02-12

### Fixed
* Vertical alignment issues using OTF and TTF files in desktop applications that differ from previous
  Font Awesome versions (< 5.7.0)

---

## [5.7.1](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.7.1) - 2019-02-01

### Fixed
* The @fortawesome/fontawesome-pro package had a corrupted SVG webfont file for the solid style
_* IE11 error reporting Promise as undefined or finally() not a function_
* The cheese has been moved on top of the patty for cheeseburger

---

## [5.7.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.7.0) - 2019-01-28

**Minor version upgrade notice: there are some backward-incompatible changes to this release. See the
[UPGRADING.md guide](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md) for more
information.**

### Added
* New Food category
* More Medical icons
* More icons from the leaderboard
* Added tasks-alt
* New CSS class fa-flip-both that applies fa-flip-horizontal and fa-flip-vertical together
* CSS now defaults to font-display: auto
* Sass and Less files contain a variable that can be changed to alter the font-display value

### Changed
* Updated slack brand icon
* Reverted calendar-alt to previous design before 5.6.0

### Fixed
_* Safari fails to process pseudo elements if the font-weight is "normal"_
* Renamed internal method to keep from confusing rJS FortAwesome/Font-Awesome#14461
* Corrected font weights in TTF files FortAwesome/Font-Awesome#13320
* XCode now correctly displays different styles when using TTF files
* Support for Turbolinks without modifying the dom.watch() call FortAwesome/Font-Awesome#12709
* Add focusable=false for SVG elements to prevent IE11 double-focus bug FortAwesome/Font-Awesome#13155

---

**Comment by DL6ER** [comment]
Thanks, it wouldn't have had to be that extensive.

> I think software should stay up to date with their assets even there are no "super new" features. Investigating a bug in safari version xy is way more time-expensive than keeping assets up to date.

I agree and my comment was more because I'm interested in the changes to see if there is something new we can benefit from. There was never a need to justify the update as such.

My review fill follow later today when I have more time. Thanks again for your contribution!

**Comment by Pazekal90** [comment]
No Problem :) I wanted to be extension for better documentation. :)

**Comment by Mcat12** [comment]
Base your branch on the dev branch, as per the contributor's guide.

**Comment by Pazekal90** [comment]
@Mcat12 Sorry. Done that.

**Pull request merged**
