### PR TITLE
Delete the unused .pullapprove.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [ ] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

### CODE REVIEW

**Comment by PromoFaux** [comment]
@dschaper we're no longer using PA, are we? If not, this file can probably go the distance...

**Comment by XhmikosR** [comment]
If it's not used fine by me

**Comment by DL6ER** [comment]
Waiting for @dschaper's final go on this.

**Comment by dschaper** [comment]
PA's been gone for a while. And I don't see this repo needing PA v3's features.

**Comment by XhmikosR** [comment]
You can change this when merging + squashing.

**Comment by DL6ER** [comment]
True, however, we consider it good practice that the PR submitter gives a short description. It also has to do with legal stuff like preventing the risk of incorporating code that could later be subject to copyright issues. You click the check boxes and write something. A simply one-liner is sufficient.

We put these restrictions on every contributor. This includes internal and external. Even at times, when I open half a dozen PRs a day, I complete the template. I know it is not the nicest thing to do, however, it is a necessary (but small) burden.

**Comment by XhmikosR** [comment]
This is totally unnecessary for internal contributors, but anyway.

**Comment by PromoFaux** [comment]
Top tip :

Github Saved replies. I just delete the template when opening a new PR, and stick in a canned response + brief description of what the PR does.

```
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
[Description here]
```

**Pull request merged**
