### PR TITLE
Improve API calls for Top Clients and Forward Destinations

### PR DESCRIPTION
**Pull request by DL6ER**
Changes proposed in this pull request:

- Try to resolve client and upstream DNS server IPs to host names if corresponding settings are `true`

Upstream DNS servers: `API_GET_UPSTREAM_DNS_HOSTNAME`
Clients: `API_GET_CLIENT_HOSTNAME`

- General speed improvements

`http://pi.hole/admin/api.php?getForwardDestinations`
`devel`: 5.8s
this PR: 3.3s

`http://pi.hole/admin/api.php?getQuerySources`
`devel`: 15.6s
this PR: 4.6s

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Will this add lots of extra queries to the log?

**Comment by DL6ER** [comment]
It will add (max) 20 PTR requests each time. However, we will exclude `[PTR]` from being show in the query log in the future.

**Comment by PromoFaux** [comment]
Hmmm, something in this PR set my `PIHOLE_DNS_2` to `none`

I thought that was fixed in devel?

**Comment by PromoFaux** [comment]
Approved

**Comment by DL6ER** [comment]
> Hmmm, something in this PR set my PIHOLE_DNS_2 to none
> I thought that was fixed in devel?

Yes, I guess the branch was not up-to-date with `devel`. Should anyhow not cause problems when merged.

**Pull request merged**
