### PR TITLE
[WIP] Show more details for forwarded queries

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Show more details for forwarded queries (if available):
screenshot at 2018-02-08 20-37-12

**How does this PR accomplish the above?:**

Process further data obtained through the API

**What documentation changes (if any) are needed to support this PR?:**

Not necessary.

### CODE REVIEW

**Comment by DL6ER** [comment]
screenshot at 2018-02-11 18-02-12

**Comment by DL6ER** [comment]
I'm not sure if that is now too much of information and distracting.

**Comment by dschaper** [comment]
Record Type is nice to have, but I'm not sold on the TTL. That's mostly out of the control of the users so it may just be extra data that doesn't need to be on the screen.

**Comment by DL6ER** [comment]
screenshot at 2018-02-16 20-34-30

**Comment by DL6ER** [comment]
Closing in favour of #694

**Pull request closed without merging**
