### PR TITLE
Advanced stats

### PR DESCRIPTION
**Pull request by bricej13**
Let's try this again.

I merged the changes into the devel branch changes. I ripped out the datatables piece as data.php isn't creating the proper data to support it.

Here's the original pull request info:
#### Added the following UI elements:
- A graph of queries over time
- Top chart of valid queries
- Top chart of advertisement queries
- Chart of most recent queries
- Removed 'More Info ->' links from top boxes to reduce confusion

#### Architecture changes
- sed/awk/wc replaced with PHP
- Moved data generation to separate file data.php file
- Data.php is used both in index.html and api.php

screen shot 2016-01-27 at 11 19 20 pm

### CODE REVIEW

**Comment by Mcat12** [comment]
You have a merge conflict in api.php

**Comment by DonLexos** [comment]
Played with this and it looks great! Not entirely sure what is causing the conflict (getting used to how github and the github software works), noticed your version on the bottom is 2.2 and the master is at 2.4 so could be you based this on that code?

**Comment by Mcat12** [comment]
The current versioning system is based on the Pi-hole, not the web interface. I'm currently changing it so that there will be separate versions for both. If you look in api.php, you'll see two versions of it, separated by a divider. You need to choose one or combine them. You do this by just modifying the file to how you want it to look (removing the stuff git put in). You can read more about it [here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merge-Conflicts).

**Comment by Mcat12** [comment]
You should move your JS code to index, after php loads in the footer. Only the index needs that code, and it will error on the list pages.

**Comment by Mcat12** [comment]
You may want to look into using ajax (through jQuery) to populate the tables. This will lower the load time of the page (which is a little long right now).

**Comment by bricej13** [comment]
I fixed the merge conflict in api.php and moved the JS code to index.php. 

Using Ajax is a good idea. This would make it feasible to load entire lists instead of the first few elements. 

@Mcat12 would you rather I create a new branch for adding the Ajax functionality or tack it on to this one?

**Comment by Mcat12** [comment]
You can work on it in this one. Also, maybe you should separate out the original api from the other stuff. This will allow you to load the original stats with the page and use ajax for the lists of domains and such.

**Comment by Mcat12** [comment]
Are your calculations taking in to account ipv6? It's doubling the amount. Remember that users could have either ipv4 or both.

**Comment by PromoFaux** [comment]
Ah yeah, you need to test for IPv6, which is pretty much as simple as checking for the existence of `/etc/pihole/.useIPv6`

From `chronometer.sh`:

```BASH
function CalcBlockedDomains(){
	CheckIPv6
	if [ -e "$gravity" ]; then
		#Are we IPV6 or IPV4?
		if [[ -n $piholeIPv6 ]];then
			#We are IPV6
			blockedDomainsTotal=$(wc -l /etc/pihole/gravity.list | awk '{print $1/2}')
		else
			#We are IPV4
			blockedDomainsTotal=$(wc -l /etc/pihole/gravity.list | awk '{print $1}')
		fi
	else
		blockedDomainsTotal="Err."
	fi
}
```
```BASH 
function CheckIPv6(){
	piholeIPv6file="/etc/pihole/.useIPv6"
	if [[ -f $piholeIPv6file ]];then
	    # If the file exists, then the user previously chose to use IPv6 in the automated installer
	    piholeIPv6=$(ip -6 route get 2001:4860:4860::8888 | awk -F " " '{ for(i=1;i<=NF;i++) if ($i == "src") print $(i+1) }')
	fi
}
```

**Comment by DonLexos** [comment]
I am not sure if I have the latest files but if I do the 2.5 release breaks a few things in the top domains/top advertisers.

**Comment by PromoFaux** [comment]
More than possible, do you have @bricej13 's version checked out on your pi? Because the changes aren't merged into the main site yet..

**Comment by DonLexos** [comment]
I grabbed it yesterday so I believe I have, but I am aware there is a merge conflict with master. Just wanted to test it out, looks good ! :-)

**Comment by PromoFaux** [comment]
I agree, I like the graphs a lot!

**Comment by PromoFaux** [comment]
But yeah, we may have broken functionality on it during the 2.5 update

**Comment by DonLexos** [comment]
Some files are moved, not sure if the logfile is filled differently with more information but instead of domain names now `query[A]` is shown. And my top advertiser is `/etc/pihole/gravity.list` :-)

Hope @bricej13 can resolve this.

**Comment by bricej13** [comment]
Made some updates: 
- Updated API to allow data to be retrieved independently
- Moved most data calls to ajax
- Fixed total blocked domains number for ipv6 users
- Fixed Top Ads & Top Queries tables to show domains properly
- Fixed time column on Recent Queries table

**Comment by Mcat12** [comment]
Good work. I'll test as soon as I get home!

**Comment by jmacdowall** [comment]
This is easy to fix.  Edit /var/www/html/admin/data.php:

Just change a couple of lines:
OLD:
<             $domain = trim($exploded[5]);
NEW:
>             $domain = trim($exploded[6]);

OLD:
<             $queryArray['domain'] = trim($exploded[5]);
<             $queryArray['ip'] = trim($exploded[7]);
NEW:
>             $queryArray['domain'] = trim($exploded[6]);
>             $queryArray['ip'] = trim($exploded[8]);


@bricej13 - sweet graph!!

**Comment by Mcat12** [comment]
What are you fixing @jmacdowall ?

**Comment by bricej13** [comment]
Looks like the fix from @jmacdowall is for the issue that @DonLexos brought up. I included that fix in the last commit.

**Comment by DonLexos** [comment]
Sounds excellent! I figured it grabbed the wrong things but did not have the time yet to go look for the fix. Will grab the latest from github and see how it works now :-)

**Comment by Mcat12** [comment]
You can run ```git remote add -t remote-branch remote-name remote-url``` To fetch a branch from a different repo. For example ```git remote add -t advancedstats bricej13 https://github.com/bricej13/AdminLTE.git```.

**Comment by Mcat12** [comment]
Them switch to it and it tracks his branch, so you can fetch/merge or pull.

**Comment by DonLexos** [comment]
Aaah ofcourse, excellent tip. I was able earlier to get the files on this repo since it is listed, maybe someone needs to merge/push/pull (I am totally unaware of some of the lingo) to make that happen, but your solution sounds like something I can make happen :-)

**Comment by DonLexos** [comment]
The Ajax way of filling the tables makes the page's initial load time much shorter. Looks good!

**Comment by Mcat12** [comment]
Instead of making branches that are copies of PRs on Github, we have decided that it is easier/more organized to make them on our local repos. So that means that if you want to test out a PR, you need to add a remote on your machine.

**Comment by bricej13** [comment]
@DonLexos That's good to hear. I'm not actually running it on a Pi, so it's always been fast for me :)

**Comment by Mcat12** [comment]
I'm still getting /etc/pihole/gravity.list among my top advertisers.

**Comment by jacobsalmela** [comment]
@Mcat12 and @bricej13 I am also getting  `/etc/pihole/gravity.list` as my top advertiser.  The interface also displays the wrong information instead of the domains.
 
screen shot 2016-02-03 at 6 37 38 pm

**Comment by Mcat12** [comment]
He updated today. Try pulling. It should be a bit better.

**Comment by jacobsalmela** [comment]
OK thanks.

**Comment by jacobsalmela** [comment]
I pulled and am up-to-date, but am still seeing this.  It might just be a PEBKAC though...

**Comment by Mcat12** [comment]
Is your branch tracking his repo? Maybe try an install.

**Comment by DonLexos** [comment]
This branch is (under this pihole admin) is 6 days old, I have no idea how that works exactly (maybe the new files need to be accepted by an admin?) bu you should be able to grab a copy here (as I did):
https://github.com/bricej13/AdminLTE/tree/advancedstats

**Comment by Mcat12** [comment]
The last commit was 1 day ago. You just need to run the command that I posted.

**Comment by Mcat12** [comment]
You may want to initially populate the stats with zeros. It looks weird while it's loading:
Screenshot

**Comment by Mcat12** [comment]
Maybe even say " - Loading" next to the titles of the various data tables/charts.

**Comment by bricej13** [comment]
Good call @Mcat12. I put some dashes in there on page load. I also went ahead and added loading indicators to the rest of the boxes on the page.

**Comment by Mcat12** [comment]
I'm getting an "address" domain with 194 hits at the top of the top advertisers list.

**Comment by DonLexos** [comment]
Hi @Mcat12 , is that still an issue now that the logfile has been rotated (at 23:50) for the next day? My top advertiser seems to be a legit one, no idea where your problem could occur from.

**Comment by Mcat12** [comment]
It's fixed now.

**Comment by Mcat12** [comment]
The x axis of the graph however jumps from 13:00 to 19:00.

**Comment by jacobsalmela** [comment]
So I got this installed and it's working quite well.  

So if I figure out how to get `www-data` the ability to modify the whitelist and blacklist files, this would probably be close to ready to merge, yes?

**Comment by Mcat12** [comment]
I think @dschaper is working on something that uses the pihole user. And when my x axis question gets answered, it might be ready.

**Comment by PromoFaux** [comment]
I've got `advancedstats` checked out on my pi, and I'm seeing entried for `name` and `/etc/pihole/gravity.list`

image

**Comment by Mcat12** [comment]
Maybe flush the log and try again.

**Comment by PromoFaux** [comment]
Done that, will update in a couple of hours.

**Comment by Mcat12** [comment]
I think maybe the reason that the x axis jumps for me is that no one is home to use the internet for a few hours. Therefore there are no DNS records for those hours.

**Comment by Mcat12** [comment]
It might be useful to hard code in the hours, but that's probably not a problem for most people.

**Comment by PromoFaux** [comment]
You'd be amazed... do you have a chromecast/nexus player? Internet connected TV? Tablet that you leave at home?

I get quite a lot of DNS requests when nobody is at home, and I'm guessing it's down to those devices!

**Comment by PromoFaux** [comment]
image
Back again!

**Comment by bricej13** [comment]
I think the issue of errant issues should be resolved now. You should only have to `git pull` and things should be fixed.

**Comment by jacobsalmela** [comment]
I just tried it on mine and even after the filesystem was expanded, it said I have insufficient space...I'll take a look at it.

**Comment by bricej13** [comment]
**More Charts!**
- Query Types: Shows what types of queries are being made (i.e. MX, AA, AAA, SOA, etc.)
- Top Clients: Shows all clients making requests and the amount of requests being made
- Forward Destinations: External DNS servers being forwarded to (i.e. 8.8.8.8, 8.8.4.4)

screen shot 2016-02-11 at 11 53 51 pm

**Comment by jacobsalmela** [comment]
Beautiful...We'll check this out.  Thanks!

**Comment by Mcat12** [comment]
Looks good. If there's any way to have all the hours of the day show up on the graph, that would be nice. Everything looks so nice!

**Comment by bricej13** [comment]
@Mcat12 I fixed the issue where hours would be missing from the graph. It should now show all hours between the first query of the day and the last.

I also added a new page (the Query Log) that has a table of all of the queries for the day.

screen shot 2016-02-13 at 12 04 24 am

**Comment by bricej13** [comment]
@jacobsalmela How are you coming on getting the whitelist/blacklist files updated? Could we strip out the editing piece for now? That would allow us to get the new dashboard out while a solution is worked on for editing the lists.

**Comment by jacobsalmela** [comment]
@bricej13 I'm good with that.  Do you want to update this PR with the white and blacklist links removed from the sidebar (and also fix the conflicts).

**Comment by Mcat12** [comment]
@jacobsalmela we can merge this and when melting into master just not merge the whitelist stuff. I think there's an option to allow you to edit the merge commit before merging.

**Comment by Mcat12** [comment]
Checkout `--no-commit`

**Comment by Mcat12** [comment]
Shoot! This touchscreen is wacky!

**Comment by Mcat12** [comment]
I was trying to comment, not close! -.-

**Comment by bricej13** [comment]
It should be ready to merge now.

**Comment by Mcat12** [comment]
Serbs stable enough here. I'll merge soon if no one objects.

**Comment by jacobsalmela** [comment]
I'm OK with it.  It's going into `devel` so we can work out any final issues there.

**Comment by PromoFaux** [comment]
Wow, this page is looking flashy as hell now. :+1:

**Comment by jacobsalmela** [comment]
+1

**Comment by DonLexos** [comment]
Loving this! One (tiny) thing, Query log time stamps are shown like `2016-02-15T02:01:04` but its `Mon 15 Feb 01:00:59 CET 2016` here now. They are 1 hour off.. and I can't figure out why.

**Comment by jmacdowall** [comment]
My timestamps are off by 4 hours—same as my time zone offset.  Coincidence?

I set the time “wrong” on my raspberry to fix it…


John MacDowall
UDP SysAdmin [Contractor]
Building 50, Room 5523
National Institutes of Heath
Bethesda, MD
301-827-4433

**Comment by DonLexos** [comment]
Oh that must be it, CET is GMT+1 .. Funny thing is, I checked the logfiles, there the time is perfect and ok, and I ran `raspi-config` to make sure it is set correctly to begin with (and it was).

**Pull request merged**
