### PR TITLE
Pi-hole Teleporter

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Add Pi-hole Takeout feature

Export your lists and settings via the web interface. Be able to import white- and blacklists (also from others).

screenshot at 2017-01-20 16-34-13

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Message shown on fresh DO Ubuntu 16.10 x64 droplet
screenshot at 2017-01-28 22-08-27

and after installing the package `php-zip`
screenshot at 2017-01-28 22-08-11

**Comment by DL6ER** [comment]
Successfully teleported exact & wildcard blacklist + whitelist from local Pi to DO droplet with two clicks.

**Comment by jacobsalmela** [comment]
@DL6ER to make this work, does Pi-hole Core need anything that's not already in the release PR?

**Comment by DL6ER** [comment]
No, pure web feature using only already existing core infrastructure

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
