### PR TITLE
list.php: wrong path to footer.php if invalid list parameter is used

### PR DESCRIPTION
**Pull request by Th3M3**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_5_

---
<pre>if($list !== "white" && $list !== "black"){
    echo "Invalid list parameter";
    require "<b>scripts/pi-hole/php/</b>footer.php";
    die();
}</pre>

Fix path to `footer.php` if an invalid list parameter is used

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Can you include an example request which would trigger this error?

**Comment by Th3M3** [comment]
> Can you include an example request which would trigger this error?

This error does not occur while normal use.
Only if the user changes or removes the `?l=` parameter in the browser's address line manually, the `Invalid list parameter` Message will be shown instead of any content.
And then the footer is missing.

Example: http://pi.hole/admin/list.php

**Comment by dschaper** [comment]
I don't think we can code solutions to protect the users if they do something intentionally to break things. It's more of a "Don't do that" issue.

**Comment by Mcat12** [comment]
We could redirect them before writing to the page, which would mean we would handle that in the header.

**Comment by Th3M3** [comment]
@dschaper I know, you're right and I don't want a protection against breaking the site.
I only wanted to point out is that the `footer.php` don't gets loaded as desired because the path is missing.

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
