### PR TITLE
Replace tab character with `\t`

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

IMHO this is clearer and doesn't depend on the editor. **This is untested** so please confirm if everything is good

### CODE REVIEW

**Comment by DL6ER** [comment]
There is a merge conflict on this.

You should be able to test this locally using
```
cd /var/www/html/admin
git checkout split-tab
```
(you may or not need `sudo` depending on the ownership of this directory)

**Comment by XhmikosR** [comment]
Fixed the conflict, my fork's develop branch was behind.

**Comment by XhmikosR** [comment]
Let's merge this so that I rebase #1080 for the last time.

**Comment by XhmikosR** [comment]
But please make sure someone tests it :)

**Comment by DL6ER** [comment]
While reviewing this PR, I found a left-over from former times where whitelisting regex filters was not yet possible.

I will remove these useless `if`s in a separate PR:

https://github.com/pi-hole/AdminLTE/blob/e1cc6a5d1fcba5808a822d9a8fc9748f1fe81be7/scripts/pi-hole/js/auditlog.js#L53-L64

https://github.com/pi-hole/AdminLTE/blob/03b3a1d6041d678e58c4aee2bd8b29d8d469f95d/api_FTL.php#L130-L133

Both times, only the `else` branch can be reached.

**Comment by XhmikosR** [comment]
Cool, closing this then

**Pull request closed without merging**
