### PR TITLE
Filter queries

### PR DESCRIPTION
**Pull request by PromoFaux**
Continuation of #136

addresses pi-hole/pi-hole#496

DO NOT MERGE YET. IT'S NOT READY

Note: this feels a lot slower than the existing admin page. I'm hardly surprised, I'm not a PHP developer!

If anyone has any suggestions to optimise.. be my guest!

@pi-hole/dashboard

### CODE REVIEW

**Comment by ChadBHowell** [comment]
@PromoFaux , is this going to filter webDomainFilter.conf also or are you going to toss everything into webClientFilter.conf?

**Comment by PromoFaux** [comment]
[Both!](https://github.com/pi-hole/AdminLTE/blob/04cc59b4aedd32fe1284ff40eae89c6aae6ca8b0/data.php#L35-L36)

**Comment by PromoFaux** [comment]
@ChadBHowell @xoniq 

How's your regex? filtering `192.168.1.1` also filters `192.168.1.1XX`

**Comment by PromoFaux** [comment]
[Probably something I'm doing here](https://github.com/pi-hole/AdminLTE/blob/04cc59b4aedd32fe1284ff40eae89c6aae6ca8b0/data.php#L301-L327)

**Comment by PromoFaux** [comment]
Note: Forward destinations chart will be inaccurate if any clients are filtered, as there is no way to determine which client the request came from. 

Domains can be done, because it contains the domain name.

**Comment by ChadBHowell** [comment]
I ran some times for you.  Commit b71c049 was used with 4 domains in webDomainFilter.conf

Master: 15.89s, 20,362 queries, 9 ads, 96,851 domains
Commit b71c049 : 35.26s, 1,933 queries, 8 ads, 96,851 domains

**Comment by PromoFaux** [comment]
Yeah, I figured there would be a performance hit... 

If you're any better at PHP than I, feel free to optimise the hell out of it and submit a PR to this branch!

**Comment by ChadBHowell** [comment]
Keep in mind that I am running pi-hole on a NTC C.H.I.P. which is NOT the fast horse in the bunch.  Maybe have the stats calculated in bash with a cron job with a settable refresh time (30s, 1m, 2m, etc).  The bash script would write to a file and the admin page would open basically instantly on the first open.  Click a refresh button on the page would manually run the bash script and update the page.  Or maybe I am just thinking crazy.... :) Great job so far BTW!

**Comment by PromoFaux** [comment]
Closing as this will be made void by #149

**Pull request closed without merging**
