### PR TITLE
Make Pi-hole logo responsive in main-sidebar

### PR DESCRIPTION
**Pull request by user501254**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_10_

---
_Small change which makes the Pi-hole logo automatically resize when the hamburger menu icon is clicked._

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
Approved

**Comment by DL6ER** [comment]
Will be reverted since it breaks compatibility with Firefox

**Comment by user501254** [comment]
I have checked on Firefox and it works just fine.

**Comment by DL6ER** [comment]
We had dozens of user reports that it didn't work.

See 
https://github.com/pi-hole/AdminLTE/issues/321 and e.g. https://discourse.pi-hole.net/t/temp-and-status-after-update-from-web-version-2-2-to-2-3-not-available/1099

**Pull request merged**
