### PR TITLE
Tidy overflow for log tailing on smaller screens

### PR DESCRIPTION
**Pull request by Toakan**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**
7
---
The following has been added to taillog and taillog-FTL in order to stop it from scrolling the screen down and prevent smaller devices (Phones / Tablets) from creating huge pages.

max-height:650px; overflow-y:scroll;

The outcome is this
image 
Compared to this.
image

It also has the benefit of preventing the bug where you cannot scroll up past the last line if the log is still generating due to requests.

A problem I have encountered, is that this breaks the "Autoscroll" button that is added. Can this be tweaked to watch the "#output" rather than the page?

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
> preventing the bug where you cannot scroll up past the last line if the log is still generating due to requests.

Out of curiosity ... have to tried to untick the checkbox on "Automatic scrolling on update"?

**Comment by Toakan** [comment]
@DL6ER Yeah I unchecked that on my phone, however it still prevented scrolling back up, not sure if a phone implementation issue or cache.

**Comment by Mcat12** [comment]
This will make scrolling work:
```javascript
if(scrolling)
{
    pre.scrollTop(pre[0].scrollHeight);
}
```

**Comment by Toakan** [comment]
@Mcat12 Sorry, it will make scrolling work where? After my code change or for all phones?

**Comment by Mcat12** [comment]
It should make scrolling work on all devices, I think.

**Comment by Toakan** [comment]
Sorry about that @Mcat12, been away for work.

Add the suggested fix to the js replacing the old. I can't actually test this currently so will either need to wait a bit to do so, or have someone else confirm it.

**Comment by Mcat12** [comment]
@Toakan could you follow these instructions so I can push a commit to this branch?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

I just have a fix so that it only scrolls down when there are new lines.

**Comment by Toakan** [comment]
Hey @Mcat12, that's already enabled for the PR.

https://i.imgur.com/vVz1AsT.png

**Comment by Mcat12** [comment]
Hm, my changes failed to push. I'll try again soon.

**Comment by Mcat12** [comment]
It looks like there's some issues coming up because you committed straight to master instead of `devel`. Can you rebase/cherrypick your commits to a new branch off of `devel`?

**Comment by Toakan** [comment]
@Mcat12 

Rebased on current origin/devel and merged to my master. If this fails out I'll try a new PR for it.

**Comment by Mcat12** [comment]
You'll probably have to cherry-pick the changes to a new branch based off of `devel`. There's many extra commits dragged into this branch.

**Comment by Toakan** [comment]
This has somehow gotten to a state where the commits are now empty and cannot be cherry picked.

Going to close this PR and submit a new one.

**Pull request closed without merging**
