### PR TITLE
Improve dropdown-menu

### PR DESCRIPTION
**Pull request by Th3M3**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

3

---
- remove border on logo
- add link feedback (on hover)
- show sessiontimer in bold letters
- use AdminLTE function to toggle dropdown-menu
- align donate-url with url in footerbar
- remove function to open user menu in footer.js

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks for the submission! I'll try and get to it tomorrow, in the mean time, any chance you can update your OP with some screenshots of the changes? thanks

**Comment by Th3M3** [comment]
Here is one screenshot:

(The Github-Link was hovered while taking the screenshot)
dropdown

**Comment by Th3M3** [comment]
...and one day I would also like to move the version infos to the dropdownmenu for smallscreens, as I have posted screenshot in #333 .

**Comment by DL6ER** [comment]
Open a PR for this :-) I'm not sure if we store the version/update information in variables, but that can be done easily and can then easily be re-used at various locations.

**Comment by DL6ER** [comment]
@Th3M3 I'm working on a major overhaul of the update notification backend. I'll include your suggestion to add it in the dropdown menu. Once this gets merged, it will most likely introduce a merge conflict with your current PR.

**Comment by Th3M3** [comment]
@DL6ER OK.
It will be the best if we close this PR. Later l will take a look into the major overhaul and how I can add my suggestions there.

**Comment by DL6ER** [comment]
No, interestingly enough, your code does not introduce any conflicts, so I'll merge it now. Please test if you see something unexpected.

**Pull request merged**
