### PR TITLE
Add Javascript Disabled Warning / Popup

### PR DESCRIPTION
**Pull request by Verpz**
This displays a small lightweight popup when a user has Javascript disabled when they load the dashboard. 

This was tested on my local Pi Hole and worked perfectly.

https://github.com/pi-hole/AdminLTE/issues/47

https://github.com/Verpz/Javascript-Disabled-Warning-Popup

### CODE REVIEW

**Comment by Mcat12** [comment]
This looks good. I'll have to look into it more! We host all of the scripts and files needed to allow the site to be viewed without an internet connection, so could you add the files to make it work offline?

**Comment by Verpz** [comment]
Yes quite easily. https://github.com/Verpz/Javascript-Disabled-Warning-Popup/blob/master/js-warn.css
That is the same CSS file is used in the CDN. Just put that somewhere locally and replace this:
```
<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/Verpz/Javascript-Disabled-Warning/53f927723dfb6ec0c9365e299dc2ed418f5c5158/js-warn.css">
```
With this:
```
<link rel="stylesheet" type="text/css" href="#path-to-css-file">
```
Also there is a minified version on the project page.

**Comment by Verpz** [comment]
I just fixed a possible conflict if you had the css id "hide" in your code. I've resolved it so please get the latest version. Don't use the CDN above to download it the new code.

**Comment by Mcat12** [comment]
You can add commits and they will show up here. So if you want, you can add the css and test it to make sure it works.

**Comment by Verpz** [comment]
It's tested and works as usual. Here is the commit https://github.com/Verpz/Javascript-Disabled-Warning-Popup/commit/b10b9ebe28a92ffe746eb7e6fb6e0d3497c3afdd

**Comment by Mcat12** [comment]
Can you save the css to a file in /css and link it that way? That's what I meant.

**Comment by Verpz** [comment]
As in, download js-warn.css and put it in /css? In that case yes, you do not have to use the CDN. Refer to my second comment.

**Comment by Verpz** [comment]
This would be the code if the css (js-warn.css) was located at /var/www/html/admin/css:
```
<!-- JS Warning -->
<div>
  <link rel="stylesheet" type="text/css" href="css/js-warn.css">
  <input type="checkbox" id="js-hide" />
  <div class="js-warn" id="js-warn-exit"><h1>Javascript Is Disabled</h1><p>Javascript seems to be disabled. This will break some site features.</p>
  <p>To enable Javascript click <a href="http://www.enable-javascript.com/" target="_blank">here</a></p><label for="js-hide">Close</label></div>
  <script>var jswarn = document.getElementById("js-warn-exit"); jswarn.parentNode.removeChild(jswarn);</script>
</div>
```
I hope that's what you meant.

**Comment by Verpz** [comment]
This would be the code if you had the css file in /var/www/html/css:
```
<!-- JS Warning -->
<div>
  <link rel="stylesheet" type="text/css" href="css/js-warn.css">
  <input type="checkbox" id="js-hide" />
  <div class="js-warn" id="js-warn-exit"><h1>Javascript Is Disabled</h1><p>Javascript seems to be disabled. This will break some site features.</p>
  <p>To enable Javascript click <a href="http://www.enable-javascript.com/" target="_blank">here</a></p><label for="js-hide">Close</label></div>
  <script>var jswarn = document.getElementById("js-warn-exit"); jswarn.parentNode.removeChild(jswarn);</script>
</div>
<!-- /JS Warning -->

**Comment by Verpz** [comment]
Here is the download link, https://github.com/Verpz/Javascript-Disabled-Warning-Popup/archive/master.zip

1. The file you want is js-warn.css or js-warn-min.css (If you want it minified).
2. Put that in /var/www/html/admin/css
3. Put this code at the top of index.php:
```
<!-- JS Warning -->
<div>
  <link rel="stylesheet" type="text/css" href="css/js-warn.css">
  <input type="checkbox" id="js-hide" />
  <div class="js-warn" id="js-warn-exit"><h1>Javascript Is Disabled</h1><p>Javascript seems to be disabled. This will break some site features.</p>
  <p>To enable Javascript click <a href="http://www.enable-javascript.com/" target="_blank">here</a></p><label for="js-hide">Close</label></div>
  <script>var jswarn = document.getElementById("js-warn-exit"); jswarn.parentNode.removeChild(jswarn);</script>
</div>
<!-- /JS Warning -->
```
Then, disable Javascript and load your dashboard. You should see the popup.
Note: if you want the minified version update the name in the second line of the code.
Also would your update script be able to download a new css file?

**Comment by Verpz** [comment]
Now the pull is setup to work for offline use.

**Comment by Mcat12** [comment]
Thank you. The update/install script installs the admin page by cloning the repo, and updates be pulling. So it will be up to date with everything we do here.

**Pull request merged**
