### PR TITLE
Import file to blacklist/whitelist

### PR DESCRIPTION
**Pull request by MASNathan**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

5

---

I've come across the need to upload a file with a list of domains to block, but there was no functionality that allowed me to do such thing.

I could eventually add an extra url to the adlist.list file but, for that, I would have to store the file somewhere.

I added a file input to the list (whitelist/blacklist) page that upon selecting a file, it'll parse it's contents and add the domains to the pihole, this will run in the background because if the file is really big, the website would become unresponsive.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Removing the styling changes would make this PR much easier to evaluate.

**Comment by DL6ER** [comment]
> I've come across the need to upload a file with a list of domains to block, but there was no functionality that allowed me to do such thing.

This is not quite true. The `Pi-hole Teleporter` actually merges the configuration it finds in the uploaded file with the local one. Hence, it can do exactly what you want.

**Comment by technicalpyro** [comment]
another option is to use nano or your favorite editor and edit the black or whitelist no?

**Comment by jacobsalmela** [comment]
@MASNathan Pi-hole Teleporter does seem to satisfy the OP.  Do you still feel your PR needs to be reviewed?  Also pinging @DL6ER and @Mcat12

**Comment by MASNathan** [comment]
No need, thats ok.

Em 07/07/2017 15:26, "Jacob Salmela" <notifications@github.com> escreveu:

@MASNathan <https://github.com/masnathan> Pi-hole Teleporter does seem to
satisfy the OP. Do you still feel your PR needs to be reviewed? Also
pinging @DL6ER <https://github.com/dl6er> and @Mcat12
<https://github.com/mcat12>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pi-hole/AdminLTE/pull/438#issuecomment-313697194>, or mute
the thread

**Pull request closed without merging**
