### PR TITLE
Restructure folders

### PR DESCRIPTION
**Pull request by DL6ER**
> DO NOT MERGE UNTIL ADAM SAYS "IT'S OK TO MERGE THIS", CAPICHE?

Internal. Assigning @dschaper and @jacobsalmela to sort out licensing. We're also going to need to change the name of the project.

@pi-hole/dashboard

### CODE REVIEW

**Comment by dschaper** [comment]
Can we revisit this now that we've removed the SELinux section from Core? If we can at least get rid of the IcoFonts and just use the glyphs required, that would be good, and should reduce our footprint by a ton.

**Comment by Mcat12** [comment]
Yes, we should look a this again. I think the only conflict was with SELinux

**Comment by PromoFaux** [comment]
Well, come to think of it, I don't think it really affected much with the SELinux stuff, considering that was broken already... I will redo this later on!

**Comment by PromoFaux** [comment]
OK, this appears to be working. Ready for check and merge

**Comment by DL6ER** [comment]
Seems to be fine. Tested on DO droplet. 

(I don't have to approve, my PR)

**Comment by Mcat12** [comment]
This will also require changing the path to the add.php script in the custom blocking page on the core repo.

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Adam says "IT'S OK TO MERGE THIS"

**Pull request merged**
