### PR TITLE
Additional Information in Pi-hole dashboard.

### PR DESCRIPTION
**Pull request by curlytailedbuffalo**
this adds some responsive datatables to the pi-hole dashboard to show the actual DNS entries and queries.

### CODE REVIEW

**Comment by Mcat12** [comment]
There were some changes to index.php made recently. You should pull those to your repo and resolve the conflicts. Also, can you merge into the devel branch?

**Comment by dschaper** [comment]
@curlytailedbuffalo Thanks for the PR, there are some conflicts like @Mcat12 mentioned. I have updated the devel branch, could you pull that branch and base your PR off of that? I don't want to manually do a merge conflict resolution as I don't know which parts of the code you'd like to update.

**Comment by Mcat12** [comment]
It may be easier to wait until #19 is merged to resolve the conflicts, because there will be some changes to the webpage files.

**Comment by Mcat12** [comment]
Can you rebase your commits onto the devel branch? That's where PRs should be merged into.

**Comment by curlytailedbuffalo** [comment]
hi sorry for the lateness, i am going to take a shot at this now, must of
had an issue with my gmail too

**Comment by Mcat12** [comment]
That's fine.

**Comment by curlytailedbuffalo** [comment]
I do have a screenshot.
One issue is I am fairly new to the git stuff, I should be editing my stuff inside the devel branch and making pull requests there?
Instead of how I did it in the master branch?

**Comment by curlytailedbuffalo** [comment]
actually, I see the note at the bottom of the readme, think that explains everything for me, ill give it a shot

**Comment by dschaper** [comment]
It's better to branch and merge to/from the devel branch, but we can adjust the PR if need be. One way or another we can get your code in!

**Comment by Mcat12** [comment]
@curlytailedbuffalo You'll want to update your fork's devel branch before you start branching off.
[This](https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/) might help.

**Comment by Mcat12** [comment]
By the way, you can embed an image with ```Some Image```

**Comment by curlytailedbuffalo** [comment]
thanks and that link will help, and for the image do you mean into the readme?

**Comment by Mcat12** [comment]
I mean, you said you had a screenshot, so I was wondering if you knew how to embed it. (The readme has the same syntax as these messages)

**Comment by curlytailedbuffalo** [comment]
pihole-datatables

**Comment by Mcat12** [comment]
Thanks!

**Comment by curlytailedbuffalo** [comment]
thanks, you guys are very helpful

**Comment by Mcat12** [comment]
[This](https://help.github.com/articles/syncing-a-fork/) might be an easier way to update your fork. It doesn't make a merge commit.

**Comment by curlytailedbuffalo** [comment]
thats just what i was looking for, i think i'm getting the hang of this

**Comment by Mcat12** [comment]
There's something called "rebasing", which allows you to take a string of commits and move them around. You can use this to move your commits from master to devel.

**Comment by curlytailedbuffalo** [comment]
im thinking, after looking around the devel branch, i will rewrite most of my changes to fit better with the branch - add to the object and such

**Comment by curlytailedbuffalo** [comment]
or maybe not, its using a shell script so maybe my changes fit fine, either way im going to poke around a bit more first, thanks though i will have to look into rebasing more for my future messups lol

**Comment by Mcat12** [comment]
If you'd rather rewrite, that's fine. Rebasing can be pretty complicated. :smile:

**Comment by Mcat12** [comment]
Once you finish your work, you will need to create a new pull request for merging your feature branch into devel.

**Pull request closed without merging**
