### PR TITLE
CSP Header

### LINKED ISSUE #27: Issue #194 from the main pi-hole repo
Just opening an issue here for [this](https://github.com/pi-hole/pi-hole/issues/194) issue, as it's to do with the web side of things.

### PR DESCRIPTION
**Pull request by Mcat12**
Fixes #27

Changes proposed in this pull request:

- Implement Content Security Policy

- Move JS code out of the main HTML and organized other JS

- Remove Paypal tracking pixel (the only thing that was not being loaded off of the Pi-hole)

@pi-hole/dashboard

### CODE REVIEW

**Comment by Zegnat** [comment]
Thank you for clearly documenting the reason for using `unsafe-eval` on `script-src`. But why do we require `unsafe-inline` for CSS as well? Is this something we could fix?

Is there a pull in sync with this one on the server side so the server can start sending the `Content-Security-Policy` HTTP header? pi-hole/pi-hole#491 only gave us `X-Frame-Options`.

**Comment by Mcat12** [comment]
We could probably split the CSS out as well, but there's a lot of inline styling and such. If it's worth it, I'll look into CSS. The CSP header is in [header.html](https://github.com/pi-hole/AdminLTE/blob/csp-headers/header.html#L5), because unlike X-Frame-Options it only needs to be applied to the actual interface, not the PHP as well (the header goes on top of all interface pages).

**Comment by Mcat12** [comment]
@Zegnat Does it look good to you?

**Comment by Mcat12** [comment]
Merging this will allow the other PRs to be updated to this new format.

**Comment by Zegnat** [comment]
> @Zegnat Does it look good to you?

Sure! Sorry for the late reply. This should cover most things other than the inline allowances on which I already commented. Recently, Troy Hunt made a [very good video tutorial](https://www.youtube.com/watch?v=L97wtYCqfwM) available if you want to learn more about testing and implementing CSP.

**Comment by Mcat12** [comment]
Thanks! Currently, I'm adapting the other branches to comply with CSP.

**Pull request merged**
