### PR TITLE
Add support for public Cloudflare DNS servers.

### PR DESCRIPTION
**Pull request by everettsouthwick**
Signed-off-by: Everett Southwick <everett@everettsouthwick.com>

**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

*This pull request will add support for Cloudflare's new Public DNS servers (1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, and 2606:4700:4700::1001) launched today.*

**How does this PR accomplish the above?:**

*It adds an entry to the savesettings.php containing the 2 IPv4 and 2 IPv6 addresses for Cloudflare.*

**What documentation changes (if any) are needed to support this PR?:**

*I'm not aware of any documentation changes necessary.*

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-default-support-for-cloudflare-dns/8486/6

**Comment by jmvermeulen** [comment]
Can we user the DOH (DNS over HTTPS) feature as well?

**Comment by Mcat12** [comment]
Dnsmasq does not yet support DNS over HTTPS natively, so you will have to find a custom solution for that (similar to dnscrypt).

**Comment by jmvermeulen** [comment]
From a PR standpoint the DOH support would be great. It's very new and afaik only supported by Firefox. PI hole can be a bridge between udp DNS locally to CloudFlare's DOH service.

**Pull request merged**
