### PR TITLE
added custom nameserver UI

### PR DESCRIPTION
**Pull request by danielreiser**
I've added the the ability to add custom nameservers for specific domains.
See here: https://imgur.com/zdrBxWn

**Caution before merging this into the master**, some system files need to be modified (mainly file permissions). dnsmasq.conf and all the files/folders within the /var/www/html/admin.
The best approach would be to create a new user to prevent 777 for files/folders I guess.
I am more a web gui so it'd be great to get some help here.

Furthermore reloading the dnsmasq.conf isnt't working as expected. Maybe file permissions as well?!

Right now I am working on the whitelist/blacklist within the webUI and would be thrilled if someone could fix the described problems.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
I do like this quite a bit based off the image.

As for the whitelisting, we may want to collaborate on a different branch, because I already a minimal whitelist feature that exists in the sidebar.  However, I think people want a more in-depth editor that would show what is whitelisted/what is not--maybe something that exists on it's own page.

**Comment by jacobsalmela** [comment]
OK, check out the whitelist branch for my latest additions.

**Comment by jacobsalmela** [comment]
I just installed your dashboard and I have been looking over your code. 

- So the custom nameserver is for replacing the `server=` value in `/etc/dnsmasq.conf`?  
  - Does it take into account there can only be three entries in the file?
- Are your white/black list scripts just supposed to display the values in those files?

I'll start looking at the permissions.

**Comment by danielreiser** [comment]
I implemented the above functionality for handling different environments. e.g. some internal networks require a special dns server for resolving internal tools or websites. I didn't no about the 3-server restriction. Is there any other place where we could place the custom nameservers? Maybe in /etc/resolver/domain.tld?

**Comment by jacobsalmela** [comment]
Actually, after reading some more, you might be able to have as many `sever=` entries if they are for a specific domain (i.e. `server=/google.com/1.2.3.4`)

I was able to get your interface to add the nameservers for the file by making `www-data` the owner of `/etc/dnsmasq.conf` but it didn't update on the interface, even after refreshing.

**Comment by jacobsalmela** [comment]
@danielreiser, just checking in on this PR.

**Comment by dschaper** [comment]
One last ping before closing the issue...

**Comment by jacobsalmela** [comment]
It might be a useful feature but @danielreiser has been non-communicative.

**Comment by danielreiser** [comment]
HI @jacobsalmela, sorry for not responding. I totally got hung up in another project and haven't checked this thread for a long time. Sorry for that.

**Comment by jacobsalmela** [comment]
It's no problem.  Feel free to re-submit if you want.  A lot has changed since the OP.

**Pull request closed without merging**
