### PR TITLE
Remove legends on dashboard graphs

### LINKED ISSUE #502: "Forward Destinations over Time" graph malformed with lots of resolvers
@CorralPeltzer commented on [Wed May 03 2017](https://github.com/pi-hole/pi-hole/issues/1428)

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG | ISSUE] Expected Behaviour:**

Good looking and readable graph.

**[BUG | ISSUE] Actual Behaviour:**
image

**[BUG | ISSUE] Steps to reproduce:**

- Add more than 4 forward destinations and use them for a while.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

---

@Saiboogu commented on [Tue May 09 2017](https://github.com/pi-hole/pi-hole/issues/1428#issuecomment-300359526)

If I disable the boxed layout option and make the browser window wide enough (Greater than 2/3 of a 2560x1440 display) it becomes much clearer. 
image

Maybe if the key could be shrunk somehow, the graph would have enough room on smaller screen sizes.   Make the key an icon to hover over for the list?

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_10_

---

Fixes #502 

New look (with hover tooltips, like in the main graph):

screenshot at 2017-05-13 17-31-45

screenshot at 2017-05-13 17-33-40

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
On smaller screens:
screenshot at 2017-05-13 17-39-36

**Comment by DL6ER** [comment]
(Emulated) Samsung Galaxy S5:
pi hole-admin-index php-login galaxy s5 1

**Comment by DL6ER** [comment]
Screenshots from an Android device.

Before:
screenshot_20170513-174831 resized

After:
screenshot_20170513-175110 resized

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
