### PR TITLE
Display CPU and I/O utilization (load)

### PR DESCRIPTION
**Pull request by DL6ER**
Changes proposed in this pull request:
- Display load.
Color: green if load was small/equal to 2.0 during the last minute, red otherwise.

The three columns measure CPU and I/O utilization of the last one, five, and 15 minute periods and are commonly used in the Linux world.

untitled24

@pi-hole/dashboard

### CODE REVIEW

**Comment by DL6ER** [comment]
Added RAM usage display
untitled84651

Computed as:
```
                   Total installed memory (memory + swap)
value = ------------------------------------------------------------
         Used memory (calculated as total - free - buffers - cache)
```

**Comment by DL6ER** [comment]
Updated formula to show the same percentage as other popular tools like system monitor, etc.

```
         Used memory (calculated as used - buffers - cache)
value = ----------------------------------------------------
               Total installed memory (memory + swap)
```

**Comment by DL6ER** [comment]
Now the displayed color depends on the number of actually available cores on the machine: 1.0 on a single core machine means it's using the CPU to it's maximum, and anything above that means things are getting queued (-> red color). E.g. the load on a RPi 1 wil always > 1 while it has only one core when updating the webinterface as all API queries are worked on in parallel.

Similar holds for multi-processor environments.

**Comment by dschaper** [comment]
Since this is just a status update with icon, and not a metric that will be tracked, I don't have the same problem with it that I had with the other PR and the graphing. I'm good with this one. (I don't approve on this repo, but I do think this should get a +1)

**Comment by PromoFaux** [comment]
Approved pending Conflict resolution.

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
