### PR TITLE
Tweak Custom DNS page

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Improve on and unify style of custom DNS configuration page.

**How does this PR accomplish the above?:**

- Move nav item further down
- Add a proper box for adding domain/IP combos
- Add a short description of what can be done on this page

&nbsp;**Before**
Screenshot at 2019-12-20 17-21-12

&nbsp;**Now**
Screenshot at 2019-12-20 17-21-00

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/web-ui-for-fqdn-lan-list/27400/3

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/custom-dns-observations/27533/3

**Comment by cyrus104** [comment]
Requesting a CSV upload and export for this capability.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).

**Pull request merged**
