### PR TITLE
Sync devel and master

### PR DESCRIPTION
**Pull request by DL6ER**
Internal

### CODE REVIEW

**Comment by Mcat12** [comment]
We shouldn't need to sync master and dev, only difference is a merge commit.

**Comment by DL6ER** [comment]
We needed it on pi-hole/pi-hole as GitHub didn't do it automatically but complained that the branches are "out of sync". The automated function offered to bring them back into sync state failed several times - it errors that it does not have permission to do so, because both `master` and `development` have the pullapprove restrictions.

**Comment by Mcat12** [comment]
How about we check if that will be the case for the next release, or if it was just a Github fluke? When the next release PR opens, we'll see if this is needed.

**Comment by DL6ER** [comment]
Okay. We can leave this open and close it if not needed later on.

**Pull request merged**
