### PR TITLE
Datatables on main index

### PR DESCRIPTION
**Pull request by curlytailedbuffalo**
add datatables on main index with the actual dns entries being queried and being blocked.
makes datables responsive as well.

see screenshot below...
adminlte-pihole-datatables

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks, I'll merge this to an alpha branch to test out!

**Comment by dschaper** [comment]
Alpha Branch https://github.com/pi-hole/AdminLTE/tree/curlytailedbuffalo-datatables

**Comment by curlytailedbuffalo** [comment]
awesome, glad to contribute

**Comment by jacobsalmela** [comment]
This looks pretty cool.  Thanks!

**Comment by Mcat12** [comment]
Right now the only issue I see is that the php takes a long time to load all of the DNS records. Maybe limit it to loading the first 500 or so?

**Comment by curlytailedbuffalo** [comment]
ive actually just started noticing that as well on my own system as the query numbers get large, to do that would i just do as i did before, make the changes and then create a new pull request?

**Comment by dschaper** [comment]
You can just continue to make changes and push to this PR, it will update the PR as you make your pushes.

**Comment by Mcat12** [comment]
We have this implemented in #25, closing.

**Pull request closed without merging**
