### PR TITLE
Improve dropdown/multiselect absolute positioning code

### PR DESCRIPTION
**Pull request by trillaxe**
Signed-off-by: trillaxe <trillax@tutanota.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

- The ability to set the position of dropdown from anywhere, e.g after selecting an option.
- Fix a bug that occurs when table is redrawn (selecting next/previous) while dropdown is visible.

**How does this PR accomplish the above?:**

By extracting the code within onDropdownShown to it's own function, it allows us to set the position of a dropdown from anywhere in the code e.g right after selecting an option which sometimes shifts the multiselect button's position.

Remove visible dropdown when the table is redrawn to prevent orphaning.

The changes
- uses the ul element (dropdown) instead of the container (which includes the button)
- add horizontal shift calculation for small screen sizes
- remove any visible dropdown upon table redraw
- reposition of dropdown when selecting options
- comments

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by trillaxe** [comment]
@DL6ER @dschaper  i would like to know if i can instead modify the **bootstrap-multiselect.js** so i don't have to put functions that are related to multiselect in groups-common.js?

Was thinking of adding something like **"detachMode"** boolean option and set **positionDropdown** as a method.

**Comment by DL6ER** [comment]
> if i can instead modify the `bootstrap-multiselect.js` so i don't have to put functions that are related to multiselect in `groups-common.js`?

Your changes would be overwritten when we update this library. We refrain from modifying anything vencor-provided to prevent such issues. I can only speak for myself, but I will likely have forgotten about this modification next year so an update would introduce a new bug.

This doesn't seem like a good idea.

**Comment by trillaxe** [comment]
I see mmhh i just don't quite like putting it in groups-common.js since it might be used somewhere else in the future. It also looks like the bootstrap-multiselect repo is no longer active (since 2018), don't quite know where to put it. Any suggestions?

**Comment by DL6ER** [comment]
Okay, if we modify the vendor file we need to make sure to not break anything accidentally when we want to update the library (assuming here there will be any updates). Any ideas for such a fail-safe switch?

**Comment by trillaxe** [comment]
The best idea i can come up with is to make a **bootstrap-multiselect-ext.js** file and but extensions in this file, this way, there would be no need to directly modify the vendor file, but where to put it?

**Comment by Th3M3** [comment]
@trillaxe @DL6ER How about using [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/examples/) plugin instead?

It has  a better positioning logic, but would need a tiny fix (css-rule) for small screens.

Currently I am testing it locally:
demo

**Comment by trillaxe** [comment]
@Th3M3 
Nice! i did some testing as well, it's actually much, much better, all you have to do is set the container option to 'body' and it just works, i'll just close this PR. :+1:

**Comment by DL6ER** [comment]
@Th3M3 Looking forward to your PR.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/web-interface-groupmanagement-shows-wrong-assignement-after-next-page/28808/7

**Comment by Th3M3** [comment]
> @Th3M3 Looking forward to your PR.

https://github.com/pi-hole/AdminLTE/pull/1186

**Pull request closed without merging**
