### PR TITLE
Temp readout fix for Pine A64

### PR DESCRIPTION
**Pull request by Fourdee**
And possibily other devices.

### CODE REVIEW

**Comment by Fourdee** [comment]
Tested on:

Odroid C2:
```
root@DietPi:~# cat /sys/class/thermal/thermal_zone0/temp; cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2
43000
43
```

Pine A64:
```
root@DietPi:~# cat /sys/class/thermal/thermal_zone0/temp; cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2
31
31
```

**Comment by PromoFaux** [comment]
Approved.

**Comment by PromoFaux** [comment]
ping! @pi-hole/dashboard

**Comment by dschaper** [comment]
Rounding up division and losing the decimal? Okay, I'm good with that.

**Comment by dschaper** [comment]
:+1:

**Comment by dschaper** [comment]
Approved

**Comment by Fourdee** [comment]
@dschaper 
> Rounding up division and losing the decimal? Okay, I'm good with that.

```
#!/bin/bash
temp=$(cat /sys/class/thermal/thermal_zone0/temp)

if (( $temp > 1000 )); then #assumes 5 digit readout

    temp=$(echo "scale=1; $temp / 1000" | bc -l )

fi

echo $temp

exit 0
```

```
root@DietPi:~# cat /sys/class/thermal/thermal_zone0/temp; ./test
41318
41.3
```

**Comment by Mcat12** [comment]
Approved

**Comment by dschaper** [comment]
@Fourdee I wasn't being sarcastic, I really was okay with no decimals in the temps.

**Pull request merged**
