### PR TITLE
updated version output

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
@pi-hole/dashboard

* removed cd from `AdminLTE` as footer.php lives in same folder and causes inconsistent behaviour if web-root changed
* changed `div style="display: inline-block"` to `span` (virtually same thing)

### CODE REVIEW

**Comment by Mcat12** [comment]
Thanks. Sorry about the other PRs. Git can be very confusing. No hard feelings!

**Comment by Mcat12** [comment]
It looks like something does change with `span`.
Screenshot

**Comment by Lewiscowles1986** [comment]
can I ask what browser that is? Here's mine (please ignore the RAM, it's virtually the same across all requests in php7)

image

**Comment by Lewiscowles1986** [comment]
looks like I forgot to change the closing tags in this PR :laughing:

**Pull request merged**
