### PR TITLE
Show disable timer across all devices

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Instead of locally we store the timeout parameter on the server. Hence, we are able to show the timeout counter across sessions, browsers and even devices.

Example: Disabled for 30 seconds on my computer, also shown on my Android device (after login in there):

screenshot_20170222-154333 resized

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
@PromoFaux 

screenshot at 2017-02-23 11-53-30

**Comment by PromoFaux** [comment]
Adds the time on much quicker than mine initial version, too ;)

Approved

**Comment by PromoFaux** [comment]
One slight bug (?) if you reenable on one device, that doesn't get reflected on the other until you reload the page...

**Comment by DL6ER** [comment]
> that doesn't get reflected on the other until you reload the page

Yes, as it is stored on the server - how should they get notified that you re-enabled it early on? There is no regular communication about that. The information on if there is a timer and how long it takes until it elapses is only transported at page loading.

**Pull request merged**
