### PR TITLE
Add CPU temp to header

### PR DESCRIPTION
**Pull request by viemmsakh**
Rename header.html to header.php

At top of header.php run shell_exec to echo the cat results of "/sys/class/thermal/thermal_zone0/temp" and assign to variable $output.

Add < li> to line 60 of new header.php that echos the contents of $output

index.php, queries.php, list.php all update require header.html to require header.php

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks @viemmsakh , we'll give it a look over.

**Comment by viemmsakh** [comment]
@PromoFaux Good deal. Here is a screenshot of the end result:

Temp

**Comment by dschaper** [comment]
What do you guys think about moving that info from the header where it is now, over to the Status Sidebar, below the Available indicator? And round it to one decimal place, I don't think we need to be quite so accurate.

**Comment by viemmsakh** [comment]
@dschaper I am happy to make that change and re-commit. You can drop a decimal by changing line 2 of header.php to
`$cmd = "echo $((`cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2`)).$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c3-4`))";`

The location could be moving line 68 to below line 174

**Comment by PromoFaux** [comment]
Could you make that change locally, with the decimal point change also, and then paste a screenshot in please?

**Comment by viemmsakh** [comment]
@PromoFaux @dschaper Sorry for the delay, am at work.

Temp in sidebar

I took a cue from your activity status and the color of the fa fa-fire icon changes depending on the temp. >45 it is red.

**Comment by dschaper** [comment]
No worries on the delay, I like the look of it. I wonder if there is a need to include `df` or `free` output on a second line below the Active and Temp?

**Comment by viemmsakh** [comment]
@dschaper Not sure I follow your `df` or `free` comment.

**Comment by dschaper** [comment]
Add the output from `df` or `free`?

**Comment by viemmsakh** [comment]
Gotcha. We could do that easily. But the size of the user-panel is based off of the pihole-160x160.jpg (which is resized to 45x45 with a padding of 10px in the div)

Adding another line without addressing the height of that div kind of mashes the text together.

**Comment by Mcat12** [comment]
This is a little bit of a nitpick, but can you please keep your spacing to spaces instead of tabs? Looks very nice! :+1:

**Comment by viemmsakh** [comment]
@Mcat12 Maybe its my editor. I cloned the repo at home here and checked one of the files that I made big changes to and its all spaces, no tabs.

**Comment by PromoFaux** [comment]
Excellent. Thanks @viemmsakh .

@pi-hole/dashboard if you're all happy with this, I think we can go ahead and merge?

**Comment by dschaper** [comment]
:+1:

**Comment by Mcat12** [comment]
Maybe add the unit to the end?

**Pull request merged**
