### PR TITLE
Added hover effect to listview

### PR DESCRIPTION
**Pull request by LasseSLambertsen**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

1
---
.skin-blue .list-group-item:hover{background: #ddd;}

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
:shipit:

**Comment by DL6ER** [comment]
Approved

**Comment by PromoFaux** [comment]
Hi there!

Thanks for your submission... I'm going to be a pain in the arse and reject this for now.. could you please add the style as an override to [this file](https://github.com/pi-hole/AdminLTE/blob/master/style/pi-hole.css)? Anything in the `vendor` directory is a bit more restrictive RE:Licensing.

(@dl6er beat me to it, but I typed this, so I'm still commenting)

**Comment by DL6ER** [comment]
Rejected

**Pull request closed without merging**
