### PR TITLE
Fix "PHP Notice:  Undefined offset:" errors

### PR DESCRIPTION
**Pull request by PromoFaux**
Mentioned by @TylonHH on [reddit](https://www.reddit.com/r/pihole/comments/52x7lc/undefined_variable/).
@pi-hole/dashboard

### CODE REVIEW

**Comment by PromoFaux** [comment]
There is still an issue with the `findAds` function

From someone on reddit:
```
2016-09-15 08:23:04: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined offset: -2 in /var/www/html/admin/data.php on line 268
2016-09-15 08:23:04: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined offset: -3 in /var/www/html/admin/data.php on line 269
2016-09-15 08:23:04: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined offset: -2 in /var/www/html/admin/data.php on line 268
2016-09-15 08:23:04: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined offset: -3 in /var/www/html/admin/data.php on line 269
```

**Comment by PromoFaux** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
bump

**Comment by jacobsalmela** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pi-hole/AdminLTE/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pi-hole/AdminLTE)

**Pull request merged**
