### PR TITLE
Remove unneeded xo suppression.

### PR DESCRIPTION
**Pull request by XhmikosR**
Signed-off-by: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

`{A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues}`

**How does this PR accomplish the above?:**

`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`

**What documentation changes (if any) are needed to support this PR?:**

`{A detailed list of any necessary changes}`

> * `{Please delete this quoted section when opening your pull request}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand an issue quicker, but please ensure it's relevant.

### CODE REVIEW

**Comment by DL6ER** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/string-content.md

Why do you want to remove this? Is it `off` by default?
I'm also thinking about future code contributions and if this rule can still be useful to reject bad things.

**Comment by XhmikosR** [comment]
Because the rule does nothing right now.. We can add it back if needed later.

**Comment by dschaper** [comment]
There's no patterns declared in the existing, correct? So it really wasn't doing anything?

**Comment by XhmikosR** [comment]
Yeah.

**Comment by XhmikosR** [comment]
BTW this targeted the devel branch, not sure if that's right. If not please cherry pick it and delete the develop branch. I didn't quite follow the changes the changes :)

**Pull request merged**
