### PR TITLE
Add option to show *all* recent queries at once

### PR DESCRIPTION
**Pull request by DL6ER**
Changes proposed in this pull request:

- Add "All" as an option:
untitled54614

At the bottom of the page, we now see
screenshot at 2016-11-14 12-51-46
ans there is only one page, as expected.

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
@Mcat12 Conflicts resolved, codacy agreed.

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
