### PR TITLE
Change wording for "Queries over Time"

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

4

---
The wording for "Queries over Time" should better reflect the fact that what's displayed is a 24 hour rolling window. As suggested per https://redd.it/68ziwx

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by DL6ER** [comment]
That is only correct if the rolling time frame window is enabled. Since it is the default with `FTL`, most users will have it. Hence,

Approved

**Comment by PromoFaux** [comment]
That is a good point. So maybe we should check to see if the non-24 hour rolling window is enabled, and have this as a dynamic string.

**Comment by DL6ER** [comment]
You have to scan `/etc/pihole/pihole-FTL.conf` for:

- `TIMEFRAME=yesterday` -> Show up to 48h (no rolling window)
- `TIMEFRAME=today` -> Show up to 24h (no rolling window)
- everything else (incl. no setting at all) -> Rolling window

**Pull request merged**
