### PR TITLE
More colours (for charts)

### PR DESCRIPTION
**Pull request by rrobgill**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**
Additional colours in the charts, to reduce colour-collision when serving more than 16 clients.
(Has been previously reported in #820 and #760 )
image

**How does this PR accomplish the above?:**
Adds additional HTML colour codes to the color array in app.min.js. These are appended to the array, beyond the default colours. 
No changes have been made to the default colours, or any colour handling code, but anything that iterates through the colour list, assigning them as it goes (eg, the clients in the clients chart) will make use of the new colours after using all of the defaults. 

**What documentation changes (if any) are needed to support this PR?:**
None.

### CODE REVIEW

**Comment by PromoFaux** [comment]
How many colours does this bring us to total? Is it worth doing some kind of "Colour.Random()" function or something?

**Comment by DL6ER** [comment]
@PromoFaux I wouldn't want to see us using even more colors in here. It's already very complicated to disentangle more than 10 clients are the colors get really close at some point.

My issue with this PR is that it modifies a vendor provided JS file, i.e., when we decide to update it at any point, we will loose the changes, except, of course, @rrobgill tells us that this is a regular new feature that will be present (to the best of his knowledge) in all newer versions of AdminLTE's `app.js`.
This is the reason why I have not approved this already.

A complete alternative would be to limit this shown clients to the ten (or so) most active clients. It's unclear how this would look like if you have a high fluctuation of clients but it would probably make the graph stay more useful for arbitrary (albeit possibly not the most extreme) situations. However, as the graph is already useless in extreme situations, it should be no worse than it is right now.

**Comment by PromoFaux** [comment]
I agree that we should probably not be making tweaks to proprietary vendor `js` files, actually. As you say, if we update to a newer version of AdminLTE, who will remember to add this change?

**Comment by rrobgill** [comment]
145.

I played around with random colours earlier. Almost every time I generated even as few as 16 randomly there were multiple near collisions - visually close enough that I couldn't pick them out (even though not numerically identical).

Think birthday problem, with the added vagaries of colour perception. It happened way more often than I expected. I assumed my code was broken, so I played around with random colours from random.org, and it did the same thing.

The checks that it would need to prevent it from happening get out of hand quickly. Would need to somehow define a reasonable distance from any existing colour, and then need some fallback once the colour space was completely full.


Limiting to the 10 most active clients would solve the problem from a colour collision perspective.

**Comment by rrobgill** [comment]
Closing - agree fully with AdminLTE upgrade concerns.

**Pull request closed without merging**
