### PR TITLE
Adding PHP password_verify as a option for stored passwords

### PR DESCRIPTION
**Pull request by invoke-Coffee**
Signed-off-by: Andrew G <andrew@invoke.coffee>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Currently Pi-hole uses sha256 for password hashing. This has several weaknesses and makes them [vulnerable to attacks](https://rietta.com/blog/bcrypt-not-sha-for-passwords/). 

This change allows these passwords to be stored using PHPs password functions. Currently this is using Bcrypt a password derivation function that is specifically designed for password storage. 
This also allows for the type of password hash to be changed going forward as upstream PHP changes the defaults and the current type is a part of the stored hash. 

**How does this PR accomplish the above?:**

The password.php will now first check for password_verify then fall back to the previous versions. 
This change will be followed up by a change in [pi-hole/advanced/Scripts/webpage.sh](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L86) to change the way the password is generated.

In the future this should also be changed to auto upgrade stored hashes. But one thing at a time. 

**What documentation changes (if any) are needed to support this PR?:**

I was not able to find any. But please let me know if I missed a place where this should be changed.

### CODE REVIEW

**Comment by dschaper** [comment]
This comes up every once in a while, please see https://github.com/pi-hole/pi-hole/issues/2168 for the discussion we had the last time.

**Comment by invoke-Coffee** [comment]
I totally get that given the security context of Pi-hole its hard to prioritize the work needed to make these changes. But that's also why I did the code change and initial testing for this to work and made this as a Pull request. 

Just to also address some other points for that discussion. 
* Additional libraries - For this (and the pi-hole changes) this will use builtin PHP functions for password_<> so no additional libraries will be added. So its a trade off on what built in libraries are used. 
* Shell script changes - I have a [commit](https://github.com/invoke-Coffee/pi-hole/commit/1c955c148555707fb7bbfdbdcc1eeae9834016c2) ready for this. But as that change depends on this one I have not yet created the Pull Request.

**Comment by DL6ER** [comment]
What is the motivation for the proposed changes? The mere "because it is better" doesn't sufficient in cryptologic thinking. The source you linked mentioned that doing "SHA* once is not sufficient". We are aware of this and never single hashed passwords.

The source you linked also contained the statement
> With a fast hash, the attacker can compute billions of hashes per second in an offline attack.

Okay, so let's assume this unspecified amount of several billions is actually 100 billions hashes per second. I think this is fair and probably even much more than they meant. As we hash twice, this number has to be divided by two giving
```
hashes_per_second = 50e9 hashes/second
```

SHA256 has an output of 256 bit length. This means
```
possible_hashes = 2^256 = 115792089237316195423570985008687907853269984665640564039457584007913129639936
```
Double hashing doesn't really change anything here.

Okay, so how many seconds does an attacker with the mentioned computing abilities need to get your password (in the worst case that they need to scan the entire range):
```
possible_hashes / hashes_per_second = 2.3158417847463238e+66 seconds
```
This is quite a lot! It is actually 48 *magnitudes* (!) larger than the age of the universe (~ 13.8 billion years).

Admittedly, above's considerations are very simple but they are rather meant to give some insight as the human's brain is really bad at thinking in very (very very!) large numbers and in orders of magnitude.

Back to your PR:

For a hash function for which L is the number of bits in the message digest, finding a message that corresponds to a given message digest can always be done using a brute force search in 2^L evaluations. This is called a [preimage attack](https://en.wikipedia.org/wiki/Preimage_attack) and may or may not be practical depending on L and the particular computing environment. We found above that it is **not practical** for SHA-256.

The second criterion, finding two different messages that produce the same message digest, known as a collision, requires on average only 2^(L/2) evaluations using a so-called [birthday attack](https://en.wikipedia.org/wiki/Birthday_attack).

The result of the birthday attach would be a password that would not be the same as the user's password, however, equally well suited to log into the Pi-hole's dashboard. The reduced complexity 
results in requiring "only" 15638091407 times the age of the universe given above's computation power.

---

However, it is important to keep in mind that even a secure password hash cannot prevent brute-force attacks on weak passwords! Even more, if a user can already gain access to the device to read the stored hash, they can equally well modify the password validation itself. In the worst case they'd just modify the SD card of the Raspberry Pi directly.

**Comment by Mcat12** [comment]
An important point from the previous discussion:
> because we can only use HTTP for transporting the password (hashed or not), there is not much point in changing it. The hashed password is effectively the password for the API already.

The attacker can simply listen in on the traffic going to the web interface to determine the hashed password. Then they can use that hashed password to log in themselves. Changing how the password is hashed will not prevent this.

**Comment by Mcat12** [comment]
Closing this until a convincing case can be made for this change.

**Pull request closed without merging**
