### PR TITLE
Updated logo to redirect user to homepage of app

### LINKED ISSUE #773: Suggestion - "Pi-hole" header logo on the top of leftnav should take you to dashboard
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1 - Casual user of pi-hole at home.

---
**Expected behaviour:**

Common UX for websites is for the icon to take you home or to the frontpage. Expected that clicking the header icon would take you there.

**Actual behaviour:**

Clicking the header icon takes you to pi-hole.net.

**Steps to reproduce:**

Click on the header icon.

**Troubleshooting undertaken, and/or other relevant information:**

It would make sense if the pi-hole.net was an entry in leftnav with its own icon.

### PR DESCRIPTION
**Pull request by Recursivepaiste**
**By submitting this pull request, I confirm the following:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Fixes #773

**How does this PR accomplish the above?:**

Added link to index file inthe anchor element. 

**What documentation changes (if any) are needed to support this PR?:**

N/A

### CODE REVIEW

**Comment by Mcat12** [comment]
Pending DCO issue resolution. See [Checks](https://github.com/pi-hole/AdminLTE/pull/854/checks) for how to sign-off your commits.

**Comment by Mcat12** [comment]
@Recursivepaiste are you having trouble signing-off your commits?

**Comment by Mcat12** [comment]
Please re-open when you are able to sign off your commits.

**Comment by ChetanGoti** [comment]
I came here to tell that, clicking on this Logo in header opens http://pi-hole.net, which prints some PHP code (instead of redirecting to HTTPS).

As is for website, I'm not sure where to report it.

image

**Comment by PromoFaux** [comment]
Thanks for the report, We'll look into it.

**Pull request closed without merging**
