### PR TITLE
open external Links in a new windows

### PR DESCRIPTION
**Pull request by TylonHH**
Hi,
ok here is my second try to understand github. I didn't edit your repo. Was that right?
I hope my suggestion push a lil bit the usability.

In my opinion external Links should open in a new windows, especially on frontends.

### CODE REVIEW

**Comment by PromoFaux** [comment]
:shipit:

**Comment by PromoFaux** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by Mcat12** [comment]
Rejected. Please base your work off of `devel` instead of `master` as the [contributing](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md) guide suggests.

**Comment by PromoFaux** [comment]
Oh! Yes, good catch. @TylonHH Please redo the changes and submit. Thanks!

**Comment by dschaper** [comment]
:+1:

**Comment by dschaper** [comment]
Approved (Need to update yamls Dan you fool...)

**Pull request closed without merging**
