### PR TITLE
improve group selection

### PR DESCRIPTION
**Pull request by Th3M3**
Signed-off-by: Th3M3 <the_me@outlook.de>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Improve multiselect (group assignment) dropdown menus

**How does this PR accomplish the above?:**

- replace `bootstrap-multiselect` plugin with [`bootstrap-select`](https://developer.snapappointments.com/bootstrap-select) ([:octocat: Repo](https://github.com/snapappointments/bootstrap-select))
- ~changed assigned groups now get applied once on dropdown-close~ 
add a `Apply` button into the dropdown menu. (Closing the dropdown menu without clicking this button will reset the selection and not apply changes)
- the table's data gets now updated after successful editing (fixes addressed issue with wrong (old) data after page switch)

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/fix-web-interface-group-multiselects/28808/8

**Comment by PromoFaux** [comment]
@Th3M3 Sorry it's taken so long for review. Please can you address the merge conflicts? Thanks!

**Comment by Th3M3** [comment]
@PromoFaux @DL6ER 
I have updated my changes and added a `Apply` button to the dropdown menu, as mentoined on discourse.

**Comment by PromoFaux** [comment]
Looks good overall, is there anything that can be done about the layout of the `select`/`deselect all` buttons? Looks a little bit squashed to my eye:

image

**Comment by Th3M3** [comment]
`bootstrap-select` allows to change the buttons textes, e.g. to just `all` and `none` [Pic. 1]
But we can also add an extra `css` rule to remove the left and right text-padding from the buttons [Pic. 2]
or hide this button bar completely [Pic. 3].

  
</div>

**Comment by PromoFaux** [comment]
`All` / `None` works for me :)

**Pull request merged**
