### PR TITLE
Add possibility to black-/whitelist entries on the Queries page.

### LINKED ISSUE #193: Feature request: adding to white/blacklist directly from the Query log
Hi,

Every now and then I see requests in the query log page that I actually do want to block but are not blocked yet. Of course (but I haven't personally encountered this situation yet), the other way around is also possible: requests that are pi-holed, but that you want to add to the white list.

If you want to make such a change in white-/blacklisting, you currently have to do this via the white-/blacklist pages. (Manually entering the domain or via a copy/paste action between those pages).

My feature request/suggestion is to be able to also do such white-/blacklisting tasks directly from the query log page in a fast and convenient way via a button after each item in the query log. ("White-/blacklist this domain" depending on its status).

Analogue to how after each row on the white-/blacklist pages, there is a trash can icon to delete the item in question.

What are your thoughts about this idea?

P.S. This is a wonderful project. I know quite a few people, including myself, who are very grateful for what it brings. :)

### PR DESCRIPTION
**Pull request by DL6ER**
Fixes #193 .

Changes proposed in this pull request:

- Add possibility to black-/whitelist entries from the queries page by a single click. 

screenshot at 2016-11-13 19-14-17

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Can you name the buttons imperatively? So "Whitelist" and "Blacklist" instead of "To ...".

**Comment by DL6ER** [comment]
@Mcat12 done.

**Comment by Mcat12** [comment]
You can also think about adding some sort of feedback for the user, like on the normal white/black listing pages where an alert thing pops up to show the status of the action.

**Comment by DL6ER** [comment]
@Mcat12 done.

untitled123123

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
Added display of which domain is going to be black-/whitelisted.

untitled4656

**Comment by PromoFaux** [comment]
Approved

**Comment by wilatai** [comment]
Fantastic! Love the buttons and the feedback of which domain is going to be black-/whitelisted.
Looking forward to testing/using it. Many thanks for your time and effort! :+1:

**Pull request merged**
