### PR TITLE
Fix black bar underneath logo

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

5

---

bug

### CODE REVIEW

**Comment by Mcat12** [comment]
Do you know if the black bar is supposed to be there as part of the theme?

**Comment by WaLLy3K** [comment]
It seems like an oversight from AdminLTE that's very easy to miss since it's normally blended in with the dark sidebar.

It appears to be caused by `min-height: 50` on `.main-header>.navbar` within `AdminLTE.min.css`. Since `.navbar` gets pushed up to 51px, it causes the black bar on the left.

**Comment by Mcat12** [comment]
This might be part of the default configuration on AdminLTE, because I know other themes let you change these thin bar colors.

**Comment by WaLLy3K** [comment]
`.main-header>.navbar` has a min-height of 50px, and I've come to realise that this appears to be stretched beyond 50px due to the `li` wrapped around #541 - this inadvertently causing a black strip under `.logo` that's only noticeable when you're changing Pi-hole setting and waiting for the rest of the page to load (upon completion of the setting change).

Therefore, it's better to fix `.navbar`'s height rather than raise `.logo`'s height.

**Pull request merged**
