### PR TITLE
Get an actual status

### PR DESCRIPTION
**Pull request by 7h3ju57**
So I had noticed a status in the top corner of the admin page but its just a static anchor.
so here's something i whipped up.

I'm open to suggestions or changes.

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
Maybe make the online pic just the normal Pi-hole logo.

**Comment by Verpz** [comment]
I agree, I think it would look a lot nicer if the normal Pi-Hole logo was still there and the status was shown by a small green or red circle. Similar to the current static element.

**Comment by jacobsalmela** [comment]
Yeah, that green circle was just a placeholder from when I first made Pi-hole.  I always meant for it to be a status indicator of whether or not it was working, so this is a cool idea.

**Comment by 7h3ju57** [comment]
Sure if you would prefer green and red dots I can switch them. I had just grabbed the pihole logo colorized it and shrank it to the size of the dot lol

**Comment by jacobsalmela** [comment]
Yeah, I think the little red/green circle will work better.  It just looks a bit cleaner.

**Comment by 7h3ju57** [comment]
Sounds good, I'll switch it up a later

**Comment by PromoFaux** [comment]
Looks good, thanks for the PR.

**Comment by jacobsalmela** [comment]
Cool.  I think this will be a nice feature.  Thanks!

**Comment by 7h3ju57** [comment]
Glad to help!

**Pull request merged**
