### PR TITLE
Don't recommend to update when on vDev

### PR DESCRIPTION
**Pull request by DL6ER**
If we are on vDev then we assume that it is always newer than the latest online release, i.e. version comparion should return 1

@pi-hole/dashboard

### CODE REVIEW

**Comment by Mcat12** [comment]
With this way of fixing the issue, we can remove some checks in lines like [this](https://github.com/pi-hole/AdminLTE/pull/231/files#diff-ce59855a9368c2740a354da467b136c6R79).

**Comment by Mcat12** [comment]
Since the `vDev` tag is functionally an alias for the development branch, we could stop checking for `vDev` and use `git rev-parse --abbrev-ref HEAD` to check if we're on `devel` or `development` instead. Then we wouldn't have to worry about the vDev tag getting messed up by a rogue merge from master (even ones that change bases via Github's PR options).

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
Approved

**Pull request merged**
