### PR TITLE
New favicons.

### PR DESCRIPTION
**Pull request by XhmikosR**
Signed-off-by: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

This is untested. Please check Chrome's application tab if everything works fine.

### CODE REVIEW

**Comment by DL6ER** [comment]
Why do we need eight different files for the favicon? And why is the only vector graphic among them (`safari-pinned-tab.svg`) b/w ?

**Comment by XhmikosR** [comment]
Because this is so that we have the best compatibility with the various browsers out there. The SVG is just for Safari pinned tabs. Every other browser will use the png files

**Comment by DL6ER** [comment]
Confirmed working with Firefox (loads `favicon-16x16.png`) and Chrome (loads `favicon.ico`).
I have no other browsers at hand to test with.

Screenshot at 2019-12-17 16-04-29
Screenshot at 2019-12-17 16-03-36

**Comment by XhmikosR** [comment]
@DL6ER can you go to Chrome devtools application tab? This branch should show 2 more icons there

**Comment by XhmikosR** [comment]
@PromoFaux can you try this in Chrome and go to devtools, Application and see if it shows 2 more icons properly there?

If all is good, this can be merged.

**Comment by PromoFaux** [comment]
Please... Manners cost nothing 😉 

I will check it later when I get home from work!

**Comment by dschaper** [comment]
What needs to be checked on this?

**Comment by XhmikosR** [comment]
In Chrome devtools -> Application you should see the big new Android icons

**Comment by dschaper** [comment]
Annotation 2020-01-18 101143

**Comment by Ghalid** [comment]
Question: Is the favicon supposed to appear blue on Safari?

Old: Screen Shot 2020-03-12 at 6 32 44 PM

New: Screen Shot 2020-03-12 at 6 32 53 PM

**Comment by dschaper** [comment]
Is the tab pinned?

**Comment by Ghalid** [comment]
> Is the tab pinned?

No. The favicon is the same regardless of if it is pinned.

**Comment by XhmikosR** [comment]
Can you remove the safari meta tag and try again? Also, if you could tell me which icon is actually loaded on Safari that has this behavior, that would help me. Oh, and just so that we are safe, try this in a private tab.

When I tried this it worked fine for me on FF and Chrome.

**Comment by dschaper** [comment]
It's doing what we told it to do, `color="#367fa9"` for theme and pinned icon. I just don't know why it's showing that for a normal favico. I have access to Safari now so I'll check and see what's up.

**Comment by Ghalid** [comment]
> Can you remove the safari meta tag and try again? Also, if you could tell me which icon is actually loaded on Safari that has this behavior, that would help me. Oh, and just so that we are safe, try this in a private tab.

The favicon looks right if I clear my website caches/other data, open a private window, and remove the line `<link rel="mask-icon" href="img/favicons/safari-pinned-tab.svg" color="#367fa9">`, not sure if that's the line you're referring to

Not exactly sure how to find what image is being used as a favicon in Safari - only images that show up under Resources are these: 
Screen Shot 2020-03-13 at 7 07 37 PM

But given that it works correctly if I remove that line, it's probably `safari-pinned-tab.svg`, even if the tab is not pinned

**Comment by XhmikosR** [comment]
Clearing cache is one step. Removing the line another one.

Since this works for me for hundreds of projects and since I don't own any Apple devices at the moment, there's nothing more I can do. I honestly don't see how the pinned tab is related to the favicon only in this project.

**Comment by dschaper** [comment]
Circling back on this. I'm seeing the proper favicon on Safari with an iPad.

**Comment by Ghalid** [comment]
Looking at it again, the correct favicon shows up on Safari on iOS for me as well. I only see the pinned (blue) favicon on Safari for macOS.

If I had to guess, macOS Safari probably shows the pinned favicon regardless, as showing favicons for all tabs only became a feature recently (and is off by default), and Safari used to only show the favicon on pinned tabs.

I actually see the correct colored favicon in the address bar when I select it, but the tab shows a blue icon:
Screen Shot 2020-04-16 at 9 18 47 PM

Screen Shot 2020-04-16 at 9 19 10 PM

**Pull request merged**
