### PR TITLE
Some more IE compatibility tricks

### LINKED ISSUE #358: IE11: Unable to whitelist from block page
@WaLLy3K commented on [Thu Jan 05 2017](https://github.com/pi-hole/pi-hole/issues/1094)

**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[ISSUE] Expected Behaviour:**
When using Internet Explorer 11 on Windows 8.1 (and presumably anything else using the Trident engine instead of EdgeHTML), I should be able to click on the "Whitelist page" button, and have it reveal the `#whitelistingform` div through the use of jQuery.

**[ISSUE] Actual Behaviour:**
The `#whitelistingform` div does not reveal itself, because the browser's error console shows `'EventSource' is undefined, File: queryads.js, Line: 19, Column: 5`. From what I understand, this appears to be [expected behaviour for IE11](http://stackoverflow.com/questions/24498141/is-there-a-microsoft-equivalent-for-html5-server-sent-events).

If I remove the line `<script src="http://pi.hole/admin/scripts/pi-hole/js/queryads.js"></script>`, I am able to reveal the div but obviously, the page does not show the results of `pihole -q $serverName -exact`

**[ISSUE] Steps to reproduce:**
Click the whitelist button when using IE11.

**Hacky but quick workaround:**
```
// Insert before line 43 of index.php
// IE11 (and older?) EventSource Workaround
if (strpos($_SERVER['HTTP_USER_AGENT'], 'Trident') !== false) {
  exec('wget -qO - "http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain="'.$serverName.'"&exact" | grep -E "list.*\([1-9]" | awk -F"[\/ ]" \'{print $6}\'', $ie11);
}

// Replace line 71
<pre id="output" style="width: 100%; height: 100%;" hidden="true"><?php if (isset($ie11)) foreach ($ie11 as $num) { echo "$num<br/>"; } ?></pre><br/>

// Replace line 91
<?php if (!isset($ie11)) echo '<script src="http://pi.hole/admin/scripts/pi-hole/js/queryads.js"></script>'; ?>
```

As a side note, I'm super impressed with the speed of `queryads.php` over just running the appropriate bash command!

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

---

@DL6ER commented on [Fri Jan 13 2017](https://github.com/pi-hole/pi-hole/issues/1094#issuecomment-272454874)

I'm thinking what we can do about it. Your solution feels way too hacky for me, but you though so already too. Maybe we should use the detection you proposed and instead just show that this feature is not available with IE.

That fells like the _best_ solution, so far.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X] - no spaces) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

(Hopefully) Fixes #358

Also some general fixes for inconsistencies which I found in the JS code.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
We could try instead simply returning the complete output after the command finishes, if the browser doesn't support EventSource.

**Comment by WaLLy3K** [comment]
Despite my attempts, I haven't figured out how to change branches and actually pull the updated files. Could someone give me the commands to do this?

The hackyness of my workaround on [pi-hole/#1094](https://github.com/pi-hole/pi-hole/issues/1094) was due to the extremely poor browser detection, and the use of `exec()`, therefore I'm also with @Mcat12 regarding providing the complete output serverside for incompatible clients. [On my version of the block page](https://github.com/WaLLy3K/Pi-hole-Block-Page/blob/aac4811c80869e6f7be3c6c40ec4d9bd5b84bf55/index.php#L153), I pull data from `queryads.php` and the final page loads within 1.0s (compared to 0.02s with JS serverside events) - though in my case, I need to do it for *everyone* as I use the returned data to provide more information to the user.

**Comment by Mcat12** [comment]
http://rogerdudler.github.io/git-guide/
Remember to run `git fetch` to get the changes from the server.

**Comment by WaLLy3K** [comment]
After a *lot* of fruitless stuffing around (and some help from @PromoFaux), I finally managed to convince git to grab the branch for me 🙌 

```
This page is blocked because it is explicitly contained within the following block list(s):
Querying ad lists is not supported with this browser!
```

**Comment by DL6ER** [comment]
@WaLLy3K Yes, that is the intermediate solution for IE. However, others seem keen to try full support of IE (which is something I wouldn't do, but Okay). This PR is not yet ready for merge. I already found a way to securely detect if `EventSource` is supported by the browser, but I still have to find the time to think of a solution that would download the full content at once in this case. I would like to do this in JS so no hacky fixes enter the PHP code. Since I'm lacking a testing environment for this, it currently does not have high priority here.

**Comment by WaLLy3K** [comment]
No worries - there's not too many Win10 holdouts left, but I'm happy to test whatever you throw out here :)

**Comment by DL6ER** [comment]
When you say

> there's not too many Win10 holdouts left

does that mean that it works with the current version of Win (which is 10, I guess)?

**Comment by WaLLy3K** [comment]
Considering that the built in browser of Windows 10 uses EdgeHTML (which is different to all prior versions which used Trident rendering), I would *assume* yes, but I would need to install a VM of W10 to test it out as I don't have it running on any computer in my house.

**Comment by DL6ER** [comment]
EventSource - supported browsers:

screenshot at 2017-01-14 10-21-16

**Comment by WaLLy3K** [comment]
Oh dear! I should say that I'm surprised...

If viewing the block list doesn't work on the latest version of Internet Explorer, then I think it's fair to say that we need to parse the list server side using PHP -- at *least* for all non EventSource supported browsers.

Having said all that, I do have to wonder out loud: What actual value is it to the client, (or the PH admin) is it to show the internal filename of the list that a domain is stored in? I think it makes far more sense to have the URL to the source list, because you get to see more than just a number of repeating `list.#.raw.githubusercontent.com.domains`

**Comment by DL6ER** [comment]
I'll have a look at this.

> Having said all that, I do have to wonder out loud: ...

Feel free to open a Feature Request on Discourse

**Comment by DL6ER** [comment]
@WaLLy3K I *potentially* found a way for supporting IE5+. Please test if you see the output. I did not implement the processing of the data, so there should be extra things like `data: ...` in each line coming up, but I'd like to know if that works at all.

**Comment by DL6ER** [comment]
@WaLLy3K Should work now. Please test Query Ad Lists (partial + exact) and blocking page. I refrain from making the Gravity page working, since there won't be any output for quite some time and if the user cancels in between he might end up with a broken Pi-hole (no adlists loaded at all or even stopped DNS service).

**Comment by Mcat12** [comment]
Those changes work for me in IE and Edge.

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
